package reposcope

import (
	"bytes"
	"crypto/sha256"
	"encoding/binary"
	"encoding/hex"
	"fmt"
	"path"
	"sort"
	"strconv"
	"strings"
	"unicode/utf8"
)

var dependencyDirectories = map[string]struct{}{
	"vendor": {}, "node_modules": {}, "third_party": {}, "third-party": {}, "external": {}, ".venv": {}, "venv": {},
}

var buildDirectories = map[string]struct{}{
	"build": {}, "dist": {}, "out": {}, "target": {}, ".next": {}, ".nuxt": {}, "coverage": {}, ".cache": {},
}

var generatedDirectories = map[string]struct{}{
	"generated": {}, "_generated": {}, "autogenerated": {}, "auto-generated": {},
}

// BuildCandidates filters an inventory through safety rules and hard scope,
// then returns candidates in language/path order. Unsafe individual entries are
// audited as rejections; malformed inventory identity or duplicate paths fail
// the whole build because they make immutable selection ambiguous.
func BuildCandidates(inventory Inventory, scope Scope, options BuildOptions) ([]Candidate, []Rejection, error) {
	if err := validateOpaqueField("commit ID", inventory.CommitID); err != nil {
		return nil, nil, fmt.Errorf("%w: %v", ErrInvalidInventory, err)
	}
	if err := validateOpaqueField("inventory ID", inventory.ID); err != nil {
		return nil, nil, fmt.Errorf("%w: %v", ErrInvalidInventory, err)
	}
	normalizedScope, err := NormalizeScope(scope)
	if err != nil {
		return nil, nil, err
	}
	maxBytes := options.MaxFileBytes
	if maxBytes == 0 {
		maxBytes = DefaultMaxFileBytes
	}
	if maxBytes < 1 || maxBytes > AbsoluteMaxFileBytes {
		return nil, nil, fmt.Errorf(
			"%w: max file bytes must be between 1 and %d",
			ErrInvalidInventory,
			AbsoluteMaxFileBytes,
		)
	}

	seenPaths := make(map[string]struct{}, len(inventory.Files))
	candidates := make([]Candidate, 0, len(inventory.Files))
	rejections := make([]Rejection, 0)
	for _, file := range inventory.Files {
		candidate, rejection := buildCandidate(inventory, normalizedScope, maxBytes, file)
		canonicalPath := file.Path
		if candidate != nil {
			canonicalPath = candidate.Path
		} else if normalized, pathErr := normalizeFilePath(file.Path); pathErr == nil {
			canonicalPath = normalized
		}
		if _, exists := seenPaths[canonicalPath]; exists {
			return nil, nil, fmt.Errorf("%w: duplicate path %q", ErrInvalidInventory, canonicalPath)
		}
		seenPaths[canonicalPath] = struct{}{}
		if rejection != nil {
			rejections = append(rejections, *rejection)
			continue
		}
		candidates = append(candidates, *candidate)
	}
	sort.Slice(candidates, func(i, j int) bool {
		if candidates[i].Language != candidates[j].Language {
			return candidates[i].Language < candidates[j].Language
		}
		return candidates[i].Path < candidates[j].Path
	})
	// Duplicate canonical paths fail above, so rejection paths are unique.
	sort.Slice(rejections, func(i, j int) bool { return rejections[i].Path < rejections[j].Path })
	return candidates, rejections, nil
}

// CandidateNeedsSample reports whether blob bytes can still affect admission
// or classification after deterministic metadata-only rejections. Callers may
// use it to avoid reading content for vendored, generated-directory, build,
// lock, empty, oversized, non-regular, or otherwise already-rejected entries.
// Unknown extensions still require a sample because a supported shebang may
// make an extensionless or unusually named script eligible.
func CandidateNeedsSample(file FileMetadata, options BuildOptions) bool {
	filePath, err := normalizeFilePath(file.Path)
	if err != nil || file.Kind != FileKindRegular ||
		hasDirectory(filePath, dependencyDirectories) || hasDirectory(filePath, buildDirectories) ||
		file.Generated || hasDirectory(filePath, generatedDirectories) || looksGenerated(filePath, nil) ||
		file.Binary || isLockFile(filePath) || file.LFS || file.Size <= 0 {
		return false
	}
	maxBytes := options.MaxFileBytes
	if maxBytes == 0 {
		maxBytes = DefaultMaxFileBytes
	}
	if maxBytes < 1 || maxBytes > AbsoluteMaxFileBytes || file.Size > maxBytes ||
		validateOpaqueField("blob ID", file.BlobID) != nil {
		return false
	}
	return true
}

func buildCandidate(inventory Inventory, scope Scope, maxBytes int64, file FileMetadata) (*Candidate, *Rejection) {
	filePath, err := normalizeFilePath(file.Path)
	if err != nil {
		return nil, reject(file.Path, RejectUnsafePath)
	}
	if file.Kind != FileKindRegular {
		return nil, reject(filePath, RejectNonRegular)
	}
	if hasDirectory(filePath, dependencyDirectories) {
		return nil, reject(filePath, RejectVendor)
	}
	if hasDirectory(filePath, buildDirectories) {
		return nil, reject(filePath, RejectBuildOutput)
	}
	sample := file.Sample
	if len(sample) > MaxSampleBytes {
		sample = sample[:MaxSampleBytes]
	}
	if file.Generated || hasDirectory(filePath, generatedDirectories) || looksGenerated(filePath, sample) {
		return nil, reject(filePath, RejectGenerated)
	}
	if file.Binary || bytes.IndexByte(sample, 0) >= 0 {
		return nil, reject(filePath, RejectBinary)
	}
	if isLockFile(filePath) {
		return nil, reject(filePath, RejectLockFile)
	}
	if file.LFS || isLFSPointer(sample) {
		return nil, reject(filePath, RejectLFS)
	}
	if file.Size <= 0 {
		return nil, reject(filePath, RejectEmpty)
	}
	if file.Size > maxBytes {
		return nil, reject(filePath, RejectOversized)
	}
	if err := validateOpaqueField("blob ID", file.BlobID); err != nil {
		return nil, reject(filePath, RejectInvalidBlob)
	}
	language, ok := DetectLanguage(filePath, sample)
	if !ok {
		return nil, reject(filePath, RejectUnknownLang)
	}
	codeType := ClassifyCodeType(filePath, language, sample)
	// The scope, path, and classifier output were canonicalized above, so this
	// internal call cannot fail. Public Scope.Allows retains validation errors.
	allowed, _ := scope.allowsNormalized(filePath, codeType)
	if !allowed {
		return nil, reject(filePath, RejectOutsideScope)
	}
	module, region, _ := DeriveLocation(filePath)
	candidate := Candidate{
		CommitID: inventory.CommitID, InventoryID: inventory.ID, Path: filePath, BlobID: file.BlobID,
		Size: file.Size, Language: language, CodeType: codeType, Region: region, Module: module,
	}
	candidate.ID = makeCandidateID(candidate)
	return &candidate, nil
}

func reject(filePath string, reason RejectionReason) *Rejection {
	return &Rejection{Path: filePath, Reason: reason}
}

func hasDirectory(filePath string, set map[string]struct{}) bool {
	parts := strings.Split(strings.ToLower(path.Dir(filePath)), "/")
	for _, part := range parts {
		if _, ok := set[part]; ok {
			return true
		}
	}
	return false
}

func looksGenerated(filePath string, sample []byte) bool {
	lowerPath := strings.ToLower(filePath)
	if strings.Contains(lowerPath, ".min.js") ||
		strings.Contains(lowerPath, ".min.css") ||
		strings.HasSuffix(lowerPath, ".pb.go") ||
		strings.HasSuffix(lowerPath, "_generated.go") ||
		strings.HasSuffix(lowerPath, ".generated.ts") ||
		strings.HasSuffix(lowerPath, ".g.cs") {
		return true
	}
	if len(sample) > 4096 {
		sample = sample[:4096]
	}
	lower := bytes.ToLower(sample)
	return bytes.Contains(lower, []byte("code generated")) && bytes.Contains(lower, []byte("do not edit")) ||
		(bytes.Contains(lower, []byte("auto-generated")) || bytes.Contains(lower, []byte("autogenerated"))) &&
			bytes.Contains(lower, []byte("do not edit"))
}

func isLockFile(filePath string) bool {
	base := strings.ToLower(path.Base(filePath))
	if strings.HasSuffix(base, ".lock") {
		return true
	}
	switch base {
	case "package-lock.json",
		"npm-shrinkwrap.json",
		"yarn.lock",
		"pnpm-lock.yaml",
		"poetry.lock",
		"pipfile.lock",
		"cargo.lock",
		"composer.lock",
		"gemfile.lock",
		"go.sum":
		return true
	default:
		return false
	}
}

func isLFSPointer(sample []byte) bool {
	return bytes.HasPrefix(bytes.TrimSpace(sample), []byte("version https://git-lfs.github.com/spec/v1"))
}

func validateOpaqueField(name, value string) error {
	if value == "" || len(value) > 512 || !utf8.ValidString(value) {
		return fmt.Errorf("%s is empty, oversized, or invalid UTF-8", name)
	}
	for _, char := range value {
		if char < 0x20 || char == 0x7f {
			return fmt.Errorf("%s contains control characters", name)
		}
	}
	return nil
}

func makeCandidateID(candidate Candidate) string {
	hash := sha256.New()
	writeHashField(hash, "reposcope-candidate-v1")
	writeHashField(hash, candidate.CommitID)
	writeHashField(hash, candidate.InventoryID)
	writeHashField(hash, candidate.Path)
	writeHashField(hash, candidate.BlobID)
	writeHashField(hash, strconv.FormatInt(candidate.Size, 10))
	writeHashField(hash, string(candidate.Language))
	writeHashField(hash, string(candidate.CodeType))
	writeHashField(hash, candidate.Region)
	writeHashField(hash, candidate.Module)
	return "cand_" + hex.EncodeToString(hash.Sum(nil))
}

type hashWriter interface {
	Write(value []byte) (written int, err error)
}

func writeHashField(writer hashWriter, value string) {
	var size [8]byte
	binary.BigEndian.PutUint64(size[:], uint64(len(value)))
	_, _ = writer.Write(size[:])
	_, _ = writer.Write([]byte(value))
}

// ValidateCandidate detects mutation of every identity and classification field.
func ValidateCandidate(candidate Candidate) error {
	if err := validateOpaqueField("commit ID", candidate.CommitID); err != nil {
		return fmt.Errorf("%w: %v", ErrInvalidCandidate, err)
	}
	if err := validateOpaqueField("inventory ID", candidate.InventoryID); err != nil {
		return fmt.Errorf("%w: %v", ErrInvalidCandidate, err)
	}
	if err := validateOpaqueField("blob ID", candidate.BlobID); err != nil {
		return fmt.Errorf("%w: %v", ErrInvalidCandidate, err)
	}
	if _, err := normalizeFilePath(candidate.Path); err != nil {
		return fmt.Errorf("%w: %v", ErrInvalidCandidate, err)
	}
	if candidate.Size < 1 || candidate.Size > AbsoluteMaxFileBytes {
		return fmt.Errorf("%w: invalid size", ErrInvalidCandidate)
	}
	if !isKnownLanguage(candidate.Language) {
		return fmt.Errorf("%w: invalid language", ErrInvalidCandidate)
	}
	if _, ok := validCodeTypes[candidate.CodeType]; !ok {
		return fmt.Errorf("%w: invalid code type", ErrInvalidCandidate)
	}
	module, region, err := DeriveLocation(candidate.Path)
	if err != nil || module != candidate.Module || region != candidate.Region {
		return fmt.Errorf("%w: invalid location classification", ErrInvalidCandidate)
	}
	if candidate.ID != makeCandidateID(candidate) {
		return fmt.Errorf("%w: identity mismatch", ErrInvalidCandidate)
	}
	return nil
}
