package reposcope

import (
	"errors"
	"strings"
	"testing"
)

func regularFile(filePath string, size int64, sample string) FileMetadata {
	return FileMetadata{
		Path:   filePath,
		BlobID: "blob:" + filePath,
		Size:   size,
		Kind:   FileKindRegular,
		Sample: []byte(sample),
	}
}

func testInventory(files ...FileMetadata) Inventory {
	return Inventory{CommitID: "commit-1", ID: "inventory-1", Files: files}
}

func TestBuildCandidatesFiltersUnsafeAndNonSourceEntries(t *testing.T) {
	files := []FileMetadata{
		regularFile("src/main.go", 8<<10, "package main"),
		regularFile("src/main_test.go", 2<<10, "func TestMain(t *testing.T) {}"),
		regularFile("../escape.go", 10, "package escape"),
		{Path: "src/link.go", BlobID: "link", Size: 10, Kind: FileKindSymlink},
		regularFile("vendor/lib/v.go", 10, "package v"),
		regularFile("build/generated.go", 10, "package generated"),
		regularFile("generated/model.go", 10, "package model"),
		{Path: "src/flag.go", BlobID: "flag", Size: 10, Kind: FileKindRegular, Generated: true},
		{Path: "src/binary.go", BlobID: "binary", Size: 10, Kind: FileKindRegular, Binary: true},
		regularFile("go.sum", 10, "module hash"),
		{Path: "src/lfs.go", BlobID: "lfs", Size: 100, Kind: FileKindRegular, LFS: true},
		regularFile("src/empty.go", 0, ""),
		regularFile("src/huge.go", DefaultMaxFileBytes+1, "package huge"),
		regularFile("src/README", 20, "not source"),
		{Path: "src/no-blob.go", Size: 20, Kind: FileKindRegular, Sample: []byte("package x")},
	}
	candidates, rejections, err := BuildCandidates(testInventory(files...), Scope{
		IncludePrefixes: []string{"src"},
		CodeTypes:       []CodeType{CodeTypeCode},
		FreeText:        "include every test too",
	}, BuildOptions{})
	if err != nil {
		t.Fatal(err)
	}
	if len(candidates) != 1 || candidates[0].Path != "src/main.go" {
		t.Fatalf("candidates = %#v", candidates)
	}
	wantReasons := map[RejectionReason]bool{
		RejectUnsafePath: true, RejectNonRegular: true, RejectVendor: true, RejectBuildOutput: true,
		RejectGenerated: true, RejectBinary: true, RejectLockFile: true, RejectLFS: true, RejectEmpty: true,
		RejectOversized: true, RejectUnknownLang: true, RejectOutsideScope: true, RejectInvalidBlob: true,
	}
	for _, rejection := range rejections {
		delete(wantReasons, rejection.Reason)
	}
	if len(wantReasons) != 0 {
		t.Fatalf("missing rejection reasons: %#v (got %#v)", wantReasons, rejections)
	}
	if err := ValidateCandidate(candidates[0]); err != nil {
		t.Fatalf("built candidate invalid: %v", err)
	}
	if candidates[0].ID == "" || !strings.HasPrefix(candidates[0].ID, "cand_") {
		t.Fatalf("candidate ID = %q", candidates[0].ID)
	}
}

func TestBuildCandidatesDetectsContentSafetySignals(t *testing.T) {
	largeSample := strings.Repeat("x", MaxSampleBytes+100) + "\x00"
	files := []FileMetadata{
		regularFile("src/nul.go", 20, "package x\x00more"),
		regularFile("src/pointer.go", 200, "  version https://git-lfs.github.com/spec/v1\noid sha256:abc"),
		regularFile("src/header.go", 100, "// Code generated by tool. DO NOT EDIT."),
		regularFile("src/auto.ts", 100, "// Auto-generated. Do not edit."),
		regularFile("src/bundle.min.js", 100, "const x=1"),
		regularFile("src/schema.pb.go", 100, "package schema"),
		regularFile("src/long.go", int64(len(largeSample)), largeSample),
	}
	_, rejections, err := BuildCandidates(testInventory(files...), Scope{}, BuildOptions{})
	if err != nil {
		t.Fatal(err)
	}
	got := make(map[string]RejectionReason)
	for _, rejection := range rejections {
		got[rejection.Path] = rejection.Reason
	}
	if got["src/nul.go"] != RejectBinary ||
		got["src/pointer.go"] != RejectLFS ||
		got["src/header.go"] != RejectGenerated ||
		got["src/auto.ts"] != RejectGenerated ||
		got["src/bundle.min.js"] != RejectGenerated ||
		got["src/schema.pb.go"] != RejectGenerated {
		t.Fatalf("unexpected content rejections: %#v", got)
	}
	// The NUL after the bounded prefix is deliberately not inspected.
	if _, ok := got["src/long.go"]; ok {
		t.Fatalf("bounded sample unexpectedly inspected tail: %#v", got)
	}
	if !looksGenerated("x_generated.go", nil) || !looksGenerated("x.g.cs", nil) ||
		!looksGenerated("x.generated.ts", nil) ||
		!looksGenerated("x.css", []byte("/* AUTOGENERATED; DO NOT EDIT */")) {
		t.Fatal("generated file signatures not recognized")
	}
}

func TestCandidateNeedsSampleSkipsDeterministicMetadataRejections(t *testing.T) {
	tests := []struct {
		path string
		size int64
		kind FileKind
		want bool
	}{
		{path: "src/main.go", size: 100, kind: FileKindRegular, want: true},
		{path: "scripts/tool", size: 100, kind: FileKindRegular, want: true},
		{path: "README.unknown", size: 100, kind: FileKindRegular, want: true},
		{path: "src/header.go", size: 100, kind: FileKindRegular, want: true},
		{path: "vendor/lib.go", size: 100, kind: FileKindRegular},
		{path: "node_modules/pkg/index.js", size: 100, kind: FileKindRegular},
		{path: "build/app.go", size: 100, kind: FileKindRegular},
		{path: "dist/app.ts", size: 100, kind: FileKindRegular},
		{path: "generated/model.go", size: 100, kind: FileKindRegular},
		{path: "src/schema.pb.go", size: 100, kind: FileKindRegular},
		{path: "go.sum", size: 100, kind: FileKindRegular},
		{path: "src/empty.go", size: 0, kind: FileKindRegular},
		{path: "src/huge.go", size: 513 << 10, kind: FileKindRegular},
		{path: "src/link.go", size: 100, kind: FileKindSymlink},
	}
	for _, test := range tests {
		file := FileMetadata{
			Path: test.path, BlobID: "blob:" + test.path, Size: test.size, Kind: test.kind,
		}
		if got := CandidateNeedsSample(file, BuildOptions{MaxFileBytes: 512 << 10}); got != test.want {
			t.Errorf("CandidateNeedsSample(%q) = %v, want %v", test.path, got, test.want)
		}
	}
	if !CandidateNeedsSample(FileMetadata{
		Path: "src/default-limit.go", BlobID: "blob:default-limit", Size: 100, Kind: FileKindRegular,
	}, BuildOptions{}) {
		t.Fatal("zero max-file option did not apply the safe default sample limit")
	}
}

func TestBuildCandidatesRejectsMalformedInventory(t *testing.T) {
	valid := regularFile("src/main.go", 100, "package main")
	tests := []struct {
		inventory Inventory
		scope     Scope
		options   BuildOptions
	}{
		{Inventory{ID: "inventory", Files: []FileMetadata{valid}}, Scope{}, BuildOptions{}},
		{Inventory{CommitID: "commit", Files: []FileMetadata{valid}}, Scope{}, BuildOptions{}},
		{Inventory{CommitID: "bad\ncommit", ID: "inventory", Files: []FileMetadata{valid}}, Scope{}, BuildOptions{}},
		{testInventory(valid), Scope{CodeTypes: []CodeType{"bad"}}, BuildOptions{}},
		{testInventory(valid), Scope{}, BuildOptions{MaxFileBytes: -1}},
		{testInventory(valid), Scope{}, BuildOptions{MaxFileBytes: AbsoluteMaxFileBytes + 1}},
		{testInventory(valid, valid), Scope{}, BuildOptions{}},
	}
	for index, test := range tests {
		if _, _, err := BuildCandidates(test.inventory, test.scope, test.options); err == nil {
			t.Errorf("case %d unexpectedly succeeded", index)
		}
	}
}

func TestCandidateIDBindsSnapshotAndClassification(t *testing.T) {
	candidates, _, err := BuildCandidates(
		testInventory(regularFile("services/api/main.go", 9000, "package api")),
		Scope{},
		BuildOptions{},
	)
	if err != nil || len(candidates) != 1 {
		t.Fatalf("build = %#v, %v", candidates, err)
	}
	base := candidates[0]
	mutations := []func(*Candidate){
		func(c *Candidate) { c.CommitID = "commit-2" },
		func(c *Candidate) { c.InventoryID = "inventory-2" },
		func(c *Candidate) { c.Path = "services/api/other.go" },
		func(c *Candidate) { c.BlobID = "blob-2" },
		func(c *Candidate) { c.Size++ },
		func(c *Candidate) { c.Language = "python" },
		func(c *Candidate) { c.CodeType = CodeTypeHotpath },
		func(c *Candidate) { c.Region = "other" },
		func(c *Candidate) { c.Module = "other/module" },
	}
	seen := map[string]bool{base.ID: true}
	for _, mutate := range mutations {
		candidate := base
		mutate(&candidate)
		candidate.ID = makeCandidateID(candidate)
		if seen[candidate.ID] {
			t.Fatalf("mutation did not change ID: %#v", candidate)
		}
		seen[candidate.ID] = true
	}

	invalid := []Candidate{base, base, base, base, base, base, base, base, base}
	invalid[0].CommitID = ""
	invalid[1].InventoryID = ""
	invalid[2].BlobID = ""
	invalid[3].Path = "../bad.go"
	invalid[4].Size = 0
	invalid[5].Language = "unknown"
	invalid[6].CodeType = "unknown"
	invalid[7].Region = "wrong"
	invalid[8].ID = "cand_tampered"
	for index, candidate := range invalid {
		if err := ValidateCandidate(candidate); !errors.Is(err, ErrInvalidCandidate) {
			t.Errorf("invalid candidate %d: %v", index, err)
		}
	}
	tooLarge := base
	tooLarge.Size = AbsoluteMaxFileBytes + 1
	if err := ValidateCandidate(tooLarge); !errors.Is(err, ErrInvalidCandidate) {
		t.Fatalf("oversized candidate error = %v", err)
	}
}

func TestLowLevelSafetyClassifiers(t *testing.T) {
	if !hasDirectory("a/node_modules/x.js", dependencyDirectories) ||
		hasDirectory("a/node_modules2/x.js", dependencyDirectories) {
		t.Fatal("dependency directory classification failed")
	}
	for _, name := range []string{"package-lock.json", "Cargo.lock", "go.sum", "custom.lock"} {
		if !isLockFile(name) {
			t.Errorf("lock file %q not recognized", name)
		}
	}
	if isLockFile("locksmith.go") || isLFSPointer([]byte("ordinary source")) {
		t.Fatal("ordinary file classified as lock/LFS")
	}
	if err := validateOpaqueField("value", strings.Repeat("x", 513)); err == nil {
		t.Fatal("oversized opaque field accepted")
	}
	if err := validateOpaqueField("value", string([]byte{0xff})); err == nil {
		t.Fatal("invalid UTF-8 opaque field accepted")
	}
}
