/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ThreadsRouteImport } from './routes/threads'
import { Route as RepositoryReviewsRouteImport } from './routes/repository-reviews'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as ModelEvaluationsRouteImport } from './routes/model-evaluations'
import { Route as LogsRouteImport } from './routes/logs'
import { Route as LauncherSetupRouteImport } from './routes/launcher-setup'
import { Route as LauncherLoginRouteImport } from './routes/launcher-login'
import { Route as EventsRouteImport } from './routes/events'
import { Route as EventSourcesRouteImport } from './routes/event-sources'
import { Route as DevelopmentRouteImport } from './routes/development'
import { Route as ConfigRouteImport } from './routes/config'
import { Route as AgentRouteImport } from './routes/agent'
import { Route as AccountsRouteImport } from './routes/accounts'
import { Route as ChannelsRouteRouteImport } from './routes/channels/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ThreadsSearchRouteImport } from './routes/threads.search'
import { Route as ThreadsOpenRouteImport } from './routes/threads.open'
import { Route as ThreadsThreadIdRouteImport } from './routes/threads.$threadId'
import { Route as RepositoryReviewsResultsRouteImport } from './routes/repository-reviews_.results'
import { Route as RepositoryReviewsRepositoriesRouteImport } from './routes/repository-reviews_.repositories'
import { Route as RepositoryReviewsProfilesRouteImport } from './routes/repository-reviews_.profiles'
import { Route as NotificationsNotificationIDRouteImport } from './routes/notifications_.$notificationID'
import { Route as ModelsRoutersRouteImport } from './routes/models_.routers'
import { Route as ModelsAliasesRouteImport } from './routes/models_.aliases'
import { Route as ModelEvaluationsNewRouteImport } from './routes/model-evaluations_.new'
import { Route as ModelEvaluationsIdRouteImport } from './routes/model-evaluations_.$id'
import { Route as DevelopmentWorkflowConfigurationsRouteImport } from './routes/development_.workflow-configurations'
import { Route as DevelopmentSettingsRouteImport } from './routes/development_.settings'
import { Route as DevelopmentRepositoriesRouteImport } from './routes/development_.repositories'
import { Route as DevelopmentNewRouteImport } from './routes/development_.new'
import { Route as DevelopmentWorkspaceIDRouteImport } from './routes/development_.$workspaceID'
import { Route as ConfigRawRouteImport } from './routes/config.raw'
import { Route as ChannelsNameRouteImport } from './routes/channels/$name'
import { Route as AgentWorkflowsRouteImport } from './routes/agent/workflows'
import { Route as AgentToolsRouteImport } from './routes/agent/tools'
import { Route as AgentSkillsRouteImport } from './routes/agent/skills'
import { Route as AgentHubRouteImport } from './routes/agent/hub'
import { Route as AgentGitWorkspacesRouteImport } from './routes/agent/git-workspaces'
import { Route as AgentAgentsRouteImport } from './routes/agent/agents'
import { Route as ThreadsOpenThreadIdRouteImport } from './routes/threads.open.$threadId'
import { Route as ModelsRoutersNewRouteImport } from './routes/models_.routers_.new'
import { Route as ModelsRoutersNameRouteImport } from './routes/models_.routers_.$name'
import { Route as ModelsAliasesNewRouteImport } from './routes/models_.aliases_.new'
import { Route as ModelsAliasesNameRouteImport } from './routes/models_.aliases_.$name'
import { Route as ModelEvaluationsIdLanguagesRouteImport } from './routes/model-evaluations_.$id_.languages'
import { Route as ModelEvaluationsIdEditRouteImport } from './routes/model-evaluations_.$id_.edit'
import { Route as ModelEvaluationsIdCorpusRouteImport } from './routes/model-evaluations_.$id_.corpus'
import { Route as ModelEvaluationsEvaluationIDReportRouteImport } from './routes/model-evaluations_.$evaluationID.report'
import { Route as AgentMcpSettingsRouteImport } from './routes/agent/mcp_.settings'
import { Route as AgentMcpServersRouteImport } from './routes/agent/mcp_.servers'
import { Route as AgentAgentsNewRouteImport } from './routes/agent/agents_.new'
import { Route as AgentAgentsIdRouteImport } from './routes/agent/agents_.$id'
import { Route as AccountsAccountRouterNewRouteImport } from './routes/accounts.account-router.new'
import { Route as AccountsAccountRouterIndexRouteImport } from './routes/accounts.account-router.$index'
import { Route as ModelsRoutersNameEditRouteImport } from './routes/models_.routers_.$name_.edit'
import { Route as ModelsAliasesNameEditRouteImport } from './routes/models_.aliases_.$name_.edit'
import { Route as AgentMcpServersNewRouteImport } from './routes/agent/mcp_.servers_.new'
import { Route as AgentMcpServersNameRouteImport } from './routes/agent/mcp_.servers_.$name'
import { Route as AgentAgentsIdEditRouteImport } from './routes/agent/agents_.$id_.edit'
import { Route as AgentAgentsIdCapabilitiesRouteImport } from './routes/agent/agents_.$id_.capabilities'
import { Route as AgentAgentsIdActivityRouteImport } from './routes/agent/agents_.$id_.activity'
import { Route as AgentMcpServersNameEditRouteImport } from './routes/agent/mcp_.servers_.$name_.edit'

const ThreadsRoute = ThreadsRouteImport.update({
  id: '/threads',
  path: '/threads',
  getParentRoute: () => rootRouteImport,
} as any)
const RepositoryReviewsRoute = RepositoryReviewsRouteImport.update({
  id: '/repository-reviews',
  path: '/repository-reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const ModelEvaluationsRoute = ModelEvaluationsRouteImport.update({
  id: '/model-evaluations',
  path: '/model-evaluations',
  getParentRoute: () => rootRouteImport,
} as any)
const LogsRoute = LogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => rootRouteImport,
} as any)
const LauncherSetupRoute = LauncherSetupRouteImport.update({
  id: '/launcher-setup',
  path: '/launcher-setup',
  getParentRoute: () => rootRouteImport,
} as any)
const LauncherLoginRoute = LauncherLoginRouteImport.update({
  id: '/launcher-login',
  path: '/launcher-login',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const EventSourcesRoute = EventSourcesRouteImport.update({
  id: '/event-sources',
  path: '/event-sources',
  getParentRoute: () => rootRouteImport,
} as any)
const DevelopmentRoute = DevelopmentRouteImport.update({
  id: '/development',
  path: '/development',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfigRoute = ConfigRouteImport.update({
  id: '/config',
  path: '/config',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentRoute = AgentRouteImport.update({
  id: '/agent',
  path: '/agent',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountsRoute = AccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => rootRouteImport,
} as any)
const ChannelsRouteRoute = ChannelsRouteRouteImport.update({
  id: '/channels',
  path: '/channels',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ThreadsSearchRoute = ThreadsSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => ThreadsRoute,
} as any)
const ThreadsOpenRoute = ThreadsOpenRouteImport.update({
  id: '/open',
  path: '/open',
  getParentRoute: () => ThreadsRoute,
} as any)
const ThreadsThreadIdRoute = ThreadsThreadIdRouteImport.update({
  id: '/$threadId',
  path: '/$threadId',
  getParentRoute: () => ThreadsRoute,
} as any)
const RepositoryReviewsResultsRoute =
  RepositoryReviewsResultsRouteImport.update({
    id: '/repository-reviews_/results',
    path: '/repository-reviews/results',
    getParentRoute: () => rootRouteImport,
  } as any)
const RepositoryReviewsRepositoriesRoute =
  RepositoryReviewsRepositoriesRouteImport.update({
    id: '/repository-reviews_/repositories',
    path: '/repository-reviews/repositories',
    getParentRoute: () => rootRouteImport,
  } as any)
const RepositoryReviewsProfilesRoute =
  RepositoryReviewsProfilesRouteImport.update({
    id: '/repository-reviews_/profiles',
    path: '/repository-reviews/profiles',
    getParentRoute: () => rootRouteImport,
  } as any)
const NotificationsNotificationIDRoute =
  NotificationsNotificationIDRouteImport.update({
    id: '/notifications_/$notificationID',
    path: '/notifications/$notificationID',
    getParentRoute: () => rootRouteImport,
  } as any)
const ModelsRoutersRoute = ModelsRoutersRouteImport.update({
  id: '/models_/routers',
  path: '/models/routers',
  getParentRoute: () => rootRouteImport,
} as any)
const ModelsAliasesRoute = ModelsAliasesRouteImport.update({
  id: '/models_/aliases',
  path: '/models/aliases',
  getParentRoute: () => rootRouteImport,
} as any)
const ModelEvaluationsNewRoute = ModelEvaluationsNewRouteImport.update({
  id: '/model-evaluations_/new',
  path: '/model-evaluations/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ModelEvaluationsIdRoute = ModelEvaluationsIdRouteImport.update({
  id: '/model-evaluations_/$id',
  path: '/model-evaluations/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DevelopmentWorkflowConfigurationsRoute =
  DevelopmentWorkflowConfigurationsRouteImport.update({
    id: '/development_/workflow-configurations',
    path: '/development/workflow-configurations',
    getParentRoute: () => rootRouteImport,
  } as any)
const DevelopmentSettingsRoute = DevelopmentSettingsRouteImport.update({
  id: '/development_/settings',
  path: '/development/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const DevelopmentRepositoriesRoute = DevelopmentRepositoriesRouteImport.update({
  id: '/development_/repositories',
  path: '/development/repositories',
  getParentRoute: () => rootRouteImport,
} as any)
const DevelopmentNewRoute = DevelopmentNewRouteImport.update({
  id: '/development_/new',
  path: '/development/new',
  getParentRoute: () => rootRouteImport,
} as any)
const DevelopmentWorkspaceIDRoute = DevelopmentWorkspaceIDRouteImport.update({
  id: '/development_/$workspaceID',
  path: '/development/$workspaceID',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfigRawRoute = ConfigRawRouteImport.update({
  id: '/raw',
  path: '/raw',
  getParentRoute: () => ConfigRoute,
} as any)
const ChannelsNameRoute = ChannelsNameRouteImport.update({
  id: '/$name',
  path: '/$name',
  getParentRoute: () => ChannelsRouteRoute,
} as any)
const AgentWorkflowsRoute = AgentWorkflowsRouteImport.update({
  id: '/workflows',
  path: '/workflows',
  getParentRoute: () => AgentRoute,
} as any)
const AgentToolsRoute = AgentToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => AgentRoute,
} as any)
const AgentSkillsRoute = AgentSkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => AgentRoute,
} as any)
const AgentHubRoute = AgentHubRouteImport.update({
  id: '/hub',
  path: '/hub',
  getParentRoute: () => AgentRoute,
} as any)
const AgentGitWorkspacesRoute = AgentGitWorkspacesRouteImport.update({
  id: '/git-workspaces',
  path: '/git-workspaces',
  getParentRoute: () => AgentRoute,
} as any)
const AgentAgentsRoute = AgentAgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => AgentRoute,
} as any)
const ThreadsOpenThreadIdRoute = ThreadsOpenThreadIdRouteImport.update({
  id: '/$threadId',
  path: '/$threadId',
  getParentRoute: () => ThreadsOpenRoute,
} as any)
const ModelsRoutersNewRoute = ModelsRoutersNewRouteImport.update({
  id: '/models_/routers_/new',
  path: '/models/routers/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ModelsRoutersNameRoute = ModelsRoutersNameRouteImport.update({
  id: '/models_/routers_/$name',
  path: '/models/routers/$name',
  getParentRoute: () => rootRouteImport,
} as any)
const ModelsAliasesNewRoute = ModelsAliasesNewRouteImport.update({
  id: '/models_/aliases_/new',
  path: '/models/aliases/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ModelsAliasesNameRoute = ModelsAliasesNameRouteImport.update({
  id: '/models_/aliases_/$name',
  path: '/models/aliases/$name',
  getParentRoute: () => rootRouteImport,
} as any)
const ModelEvaluationsIdLanguagesRoute =
  ModelEvaluationsIdLanguagesRouteImport.update({
    id: '/model-evaluations_/$id_/languages',
    path: '/model-evaluations/$id/languages',
    getParentRoute: () => rootRouteImport,
  } as any)
const ModelEvaluationsIdEditRoute = ModelEvaluationsIdEditRouteImport.update({
  id: '/model-evaluations_/$id_/edit',
  path: '/model-evaluations/$id/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const ModelEvaluationsIdCorpusRoute =
  ModelEvaluationsIdCorpusRouteImport.update({
    id: '/model-evaluations_/$id_/corpus',
    path: '/model-evaluations/$id/corpus',
    getParentRoute: () => rootRouteImport,
  } as any)
const ModelEvaluationsEvaluationIDReportRoute =
  ModelEvaluationsEvaluationIDReportRouteImport.update({
    id: '/model-evaluations_/$evaluationID/report',
    path: '/model-evaluations/$evaluationID/report',
    getParentRoute: () => rootRouteImport,
  } as any)
const AgentMcpSettingsRoute = AgentMcpSettingsRouteImport.update({
  id: '/mcp_/settings',
  path: '/mcp/settings',
  getParentRoute: () => AgentRoute,
} as any)
const AgentMcpServersRoute = AgentMcpServersRouteImport.update({
  id: '/mcp_/servers',
  path: '/mcp/servers',
  getParentRoute: () => AgentRoute,
} as any)
const AgentAgentsNewRoute = AgentAgentsNewRouteImport.update({
  id: '/agents_/new',
  path: '/agents/new',
  getParentRoute: () => AgentRoute,
} as any)
const AgentAgentsIdRoute = AgentAgentsIdRouteImport.update({
  id: '/agents_/$id',
  path: '/agents/$id',
  getParentRoute: () => AgentRoute,
} as any)
const AccountsAccountRouterNewRoute =
  AccountsAccountRouterNewRouteImport.update({
    id: '/account-router/new',
    path: '/account-router/new',
    getParentRoute: () => AccountsRoute,
  } as any)
const AccountsAccountRouterIndexRoute =
  AccountsAccountRouterIndexRouteImport.update({
    id: '/account-router/$index',
    path: '/account-router/$index',
    getParentRoute: () => AccountsRoute,
  } as any)
const ModelsRoutersNameEditRoute = ModelsRoutersNameEditRouteImport.update({
  id: '/models_/routers_/$name_/edit',
  path: '/models/routers/$name/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const ModelsAliasesNameEditRoute = ModelsAliasesNameEditRouteImport.update({
  id: '/models_/aliases_/$name_/edit',
  path: '/models/aliases/$name/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentMcpServersNewRoute = AgentMcpServersNewRouteImport.update({
  id: '/mcp_/servers_/new',
  path: '/mcp/servers/new',
  getParentRoute: () => AgentRoute,
} as any)
const AgentMcpServersNameRoute = AgentMcpServersNameRouteImport.update({
  id: '/mcp_/servers_/$name',
  path: '/mcp/servers/$name',
  getParentRoute: () => AgentRoute,
} as any)
const AgentAgentsIdEditRoute = AgentAgentsIdEditRouteImport.update({
  id: '/agents_/$id_/edit',
  path: '/agents/$id/edit',
  getParentRoute: () => AgentRoute,
} as any)
const AgentAgentsIdCapabilitiesRoute =
  AgentAgentsIdCapabilitiesRouteImport.update({
    id: '/agents_/$id_/capabilities',
    path: '/agents/$id/capabilities',
    getParentRoute: () => AgentRoute,
  } as any)
const AgentAgentsIdActivityRoute = AgentAgentsIdActivityRouteImport.update({
  id: '/agents_/$id_/activity',
  path: '/agents/$id/activity',
  getParentRoute: () => AgentRoute,
} as any)
const AgentMcpServersNameEditRoute = AgentMcpServersNameEditRouteImport.update({
  id: '/mcp_/servers_/$name_/edit',
  path: '/mcp/servers/$name/edit',
  getParentRoute: () => AgentRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/channels': typeof ChannelsRouteRouteWithChildren
  '/accounts': typeof AccountsRouteWithChildren
  '/agent': typeof AgentRouteWithChildren
  '/config': typeof ConfigRouteWithChildren
  '/development': typeof DevelopmentRoute
  '/event-sources': typeof EventSourcesRoute
  '/events': typeof EventsRoute
  '/launcher-login': typeof LauncherLoginRoute
  '/launcher-setup': typeof LauncherSetupRoute
  '/logs': typeof LogsRoute
  '/model-evaluations': typeof ModelEvaluationsRoute
  '/notifications': typeof NotificationsRoute
  '/repository-reviews': typeof RepositoryReviewsRoute
  '/threads': typeof ThreadsRouteWithChildren
  '/agent/agents': typeof AgentAgentsRoute
  '/agent/git-workspaces': typeof AgentGitWorkspacesRoute
  '/agent/hub': typeof AgentHubRoute
  '/agent/skills': typeof AgentSkillsRoute
  '/agent/tools': typeof AgentToolsRoute
  '/agent/workflows': typeof AgentWorkflowsRoute
  '/channels/$name': typeof ChannelsNameRoute
  '/config/raw': typeof ConfigRawRoute
  '/development/$workspaceID': typeof DevelopmentWorkspaceIDRoute
  '/development/new': typeof DevelopmentNewRoute
  '/development/repositories': typeof DevelopmentRepositoriesRoute
  '/development/settings': typeof DevelopmentSettingsRoute
  '/development/workflow-configurations': typeof DevelopmentWorkflowConfigurationsRoute
  '/model-evaluations/$id': typeof ModelEvaluationsIdRoute
  '/model-evaluations/new': typeof ModelEvaluationsNewRoute
  '/models/aliases': typeof ModelsAliasesRoute
  '/models/routers': typeof ModelsRoutersRoute
  '/notifications/$notificationID': typeof NotificationsNotificationIDRoute
  '/repository-reviews/profiles': typeof RepositoryReviewsProfilesRoute
  '/repository-reviews/repositories': typeof RepositoryReviewsRepositoriesRoute
  '/repository-reviews/results': typeof RepositoryReviewsResultsRoute
  '/threads/$threadId': typeof ThreadsThreadIdRoute
  '/threads/open': typeof ThreadsOpenRouteWithChildren
  '/threads/search': typeof ThreadsSearchRoute
  '/accounts/account-router/$index': typeof AccountsAccountRouterIndexRoute
  '/accounts/account-router/new': typeof AccountsAccountRouterNewRoute
  '/agent/agents/$id': typeof AgentAgentsIdRoute
  '/agent/agents/new': typeof AgentAgentsNewRoute
  '/agent/mcp/servers': typeof AgentMcpServersRoute
  '/agent/mcp/settings': typeof AgentMcpSettingsRoute
  '/model-evaluations/$evaluationID/report': typeof ModelEvaluationsEvaluationIDReportRoute
  '/model-evaluations/$id/corpus': typeof ModelEvaluationsIdCorpusRoute
  '/model-evaluations/$id/edit': typeof ModelEvaluationsIdEditRoute
  '/model-evaluations/$id/languages': typeof ModelEvaluationsIdLanguagesRoute
  '/models/aliases/$name': typeof ModelsAliasesNameRoute
  '/models/aliases/new': typeof ModelsAliasesNewRoute
  '/models/routers/$name': typeof ModelsRoutersNameRoute
  '/models/routers/new': typeof ModelsRoutersNewRoute
  '/threads/open/$threadId': typeof ThreadsOpenThreadIdRoute
  '/agent/agents/$id/activity': typeof AgentAgentsIdActivityRoute
  '/agent/agents/$id/capabilities': typeof AgentAgentsIdCapabilitiesRoute
  '/agent/agents/$id/edit': typeof AgentAgentsIdEditRoute
  '/agent/mcp/servers/$name': typeof AgentMcpServersNameRoute
  '/agent/mcp/servers/new': typeof AgentMcpServersNewRoute
  '/models/aliases/$name/edit': typeof ModelsAliasesNameEditRoute
  '/models/routers/$name/edit': typeof ModelsRoutersNameEditRoute
  '/agent/mcp/servers/$name/edit': typeof AgentMcpServersNameEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/channels': typeof ChannelsRouteRouteWithChildren
  '/accounts': typeof AccountsRouteWithChildren
  '/agent': typeof AgentRouteWithChildren
  '/config': typeof ConfigRouteWithChildren
  '/development': typeof DevelopmentRoute
  '/event-sources': typeof EventSourcesRoute
  '/events': typeof EventsRoute
  '/launcher-login': typeof LauncherLoginRoute
  '/launcher-setup': typeof LauncherSetupRoute
  '/logs': typeof LogsRoute
  '/model-evaluations': typeof ModelEvaluationsRoute
  '/notifications': typeof NotificationsRoute
  '/repository-reviews': typeof RepositoryReviewsRoute
  '/threads': typeof ThreadsRouteWithChildren
  '/agent/agents': typeof AgentAgentsRoute
  '/agent/git-workspaces': typeof AgentGitWorkspacesRoute
  '/agent/hub': typeof AgentHubRoute
  '/agent/skills': typeof AgentSkillsRoute
  '/agent/tools': typeof AgentToolsRoute
  '/agent/workflows': typeof AgentWorkflowsRoute
  '/channels/$name': typeof ChannelsNameRoute
  '/config/raw': typeof ConfigRawRoute
  '/development/$workspaceID': typeof DevelopmentWorkspaceIDRoute
  '/development/new': typeof DevelopmentNewRoute
  '/development/repositories': typeof DevelopmentRepositoriesRoute
  '/development/settings': typeof DevelopmentSettingsRoute
  '/development/workflow-configurations': typeof DevelopmentWorkflowConfigurationsRoute
  '/model-evaluations/$id': typeof ModelEvaluationsIdRoute
  '/model-evaluations/new': typeof ModelEvaluationsNewRoute
  '/models/aliases': typeof ModelsAliasesRoute
  '/models/routers': typeof ModelsRoutersRoute
  '/notifications/$notificationID': typeof NotificationsNotificationIDRoute
  '/repository-reviews/profiles': typeof RepositoryReviewsProfilesRoute
  '/repository-reviews/repositories': typeof RepositoryReviewsRepositoriesRoute
  '/repository-reviews/results': typeof RepositoryReviewsResultsRoute
  '/threads/$threadId': typeof ThreadsThreadIdRoute
  '/threads/open': typeof ThreadsOpenRouteWithChildren
  '/threads/search': typeof ThreadsSearchRoute
  '/accounts/account-router/$index': typeof AccountsAccountRouterIndexRoute
  '/accounts/account-router/new': typeof AccountsAccountRouterNewRoute
  '/agent/agents/$id': typeof AgentAgentsIdRoute
  '/agent/agents/new': typeof AgentAgentsNewRoute
  '/agent/mcp/servers': typeof AgentMcpServersRoute
  '/agent/mcp/settings': typeof AgentMcpSettingsRoute
  '/model-evaluations/$evaluationID/report': typeof ModelEvaluationsEvaluationIDReportRoute
  '/model-evaluations/$id/corpus': typeof ModelEvaluationsIdCorpusRoute
  '/model-evaluations/$id/edit': typeof ModelEvaluationsIdEditRoute
  '/model-evaluations/$id/languages': typeof ModelEvaluationsIdLanguagesRoute
  '/models/aliases/$name': typeof ModelsAliasesNameRoute
  '/models/aliases/new': typeof ModelsAliasesNewRoute
  '/models/routers/$name': typeof ModelsRoutersNameRoute
  '/models/routers/new': typeof ModelsRoutersNewRoute
  '/threads/open/$threadId': typeof ThreadsOpenThreadIdRoute
  '/agent/agents/$id/activity': typeof AgentAgentsIdActivityRoute
  '/agent/agents/$id/capabilities': typeof AgentAgentsIdCapabilitiesRoute
  '/agent/agents/$id/edit': typeof AgentAgentsIdEditRoute
  '/agent/mcp/servers/$name': typeof AgentMcpServersNameRoute
  '/agent/mcp/servers/new': typeof AgentMcpServersNewRoute
  '/models/aliases/$name/edit': typeof ModelsAliasesNameEditRoute
  '/models/routers/$name/edit': typeof ModelsRoutersNameEditRoute
  '/agent/mcp/servers/$name/edit': typeof AgentMcpServersNameEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/channels': typeof ChannelsRouteRouteWithChildren
  '/accounts': typeof AccountsRouteWithChildren
  '/agent': typeof AgentRouteWithChildren
  '/config': typeof ConfigRouteWithChildren
  '/development': typeof DevelopmentRoute
  '/event-sources': typeof EventSourcesRoute
  '/events': typeof EventsRoute
  '/launcher-login': typeof LauncherLoginRoute
  '/launcher-setup': typeof LauncherSetupRoute
  '/logs': typeof LogsRoute
  '/model-evaluations': typeof ModelEvaluationsRoute
  '/notifications': typeof NotificationsRoute
  '/repository-reviews': typeof RepositoryReviewsRoute
  '/threads': typeof ThreadsRouteWithChildren
  '/agent/agents': typeof AgentAgentsRoute
  '/agent/git-workspaces': typeof AgentGitWorkspacesRoute
  '/agent/hub': typeof AgentHubRoute
  '/agent/skills': typeof AgentSkillsRoute
  '/agent/tools': typeof AgentToolsRoute
  '/agent/workflows': typeof AgentWorkflowsRoute
  '/channels/$name': typeof ChannelsNameRoute
  '/config/raw': typeof ConfigRawRoute
  '/development_/$workspaceID': typeof DevelopmentWorkspaceIDRoute
  '/development_/new': typeof DevelopmentNewRoute
  '/development_/repositories': typeof DevelopmentRepositoriesRoute
  '/development_/settings': typeof DevelopmentSettingsRoute
  '/development_/workflow-configurations': typeof DevelopmentWorkflowConfigurationsRoute
  '/model-evaluations_/$id': typeof ModelEvaluationsIdRoute
  '/model-evaluations_/new': typeof ModelEvaluationsNewRoute
  '/models_/aliases': typeof ModelsAliasesRoute
  '/models_/routers': typeof ModelsRoutersRoute
  '/notifications_/$notificationID': typeof NotificationsNotificationIDRoute
  '/repository-reviews_/profiles': typeof RepositoryReviewsProfilesRoute
  '/repository-reviews_/repositories': typeof RepositoryReviewsRepositoriesRoute
  '/repository-reviews_/results': typeof RepositoryReviewsResultsRoute
  '/threads/$threadId': typeof ThreadsThreadIdRoute
  '/threads/open': typeof ThreadsOpenRouteWithChildren
  '/threads/search': typeof ThreadsSearchRoute
  '/accounts/account-router/$index': typeof AccountsAccountRouterIndexRoute
  '/accounts/account-router/new': typeof AccountsAccountRouterNewRoute
  '/agent/agents_/$id': typeof AgentAgentsIdRoute
  '/agent/agents_/new': typeof AgentAgentsNewRoute
  '/agent/mcp_/servers': typeof AgentMcpServersRoute
  '/agent/mcp_/settings': typeof AgentMcpSettingsRoute
  '/model-evaluations_/$evaluationID/report': typeof ModelEvaluationsEvaluationIDReportRoute
  '/model-evaluations_/$id_/corpus': typeof ModelEvaluationsIdCorpusRoute
  '/model-evaluations_/$id_/edit': typeof ModelEvaluationsIdEditRoute
  '/model-evaluations_/$id_/languages': typeof ModelEvaluationsIdLanguagesRoute
  '/models_/aliases_/$name': typeof ModelsAliasesNameRoute
  '/models_/aliases_/new': typeof ModelsAliasesNewRoute
  '/models_/routers_/$name': typeof ModelsRoutersNameRoute
  '/models_/routers_/new': typeof ModelsRoutersNewRoute
  '/threads/open/$threadId': typeof ThreadsOpenThreadIdRoute
  '/agent/agents_/$id_/activity': typeof AgentAgentsIdActivityRoute
  '/agent/agents_/$id_/capabilities': typeof AgentAgentsIdCapabilitiesRoute
  '/agent/agents_/$id_/edit': typeof AgentAgentsIdEditRoute
  '/agent/mcp_/servers_/$name': typeof AgentMcpServersNameRoute
  '/agent/mcp_/servers_/new': typeof AgentMcpServersNewRoute
  '/models_/aliases_/$name_/edit': typeof ModelsAliasesNameEditRoute
  '/models_/routers_/$name_/edit': typeof ModelsRoutersNameEditRoute
  '/agent/mcp_/servers_/$name_/edit': typeof AgentMcpServersNameEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/channels'
    | '/accounts'
    | '/agent'
    | '/config'
    | '/development'
    | '/event-sources'
    | '/events'
    | '/launcher-login'
    | '/launcher-setup'
    | '/logs'
    | '/model-evaluations'
    | '/notifications'
    | '/repository-reviews'
    | '/threads'
    | '/agent/agents'
    | '/agent/git-workspaces'
    | '/agent/hub'
    | '/agent/skills'
    | '/agent/tools'
    | '/agent/workflows'
    | '/channels/$name'
    | '/config/raw'
    | '/development/$workspaceID'
    | '/development/new'
    | '/development/repositories'
    | '/development/settings'
    | '/development/workflow-configurations'
    | '/model-evaluations/$id'
    | '/model-evaluations/new'
    | '/models/aliases'
    | '/models/routers'
    | '/notifications/$notificationID'
    | '/repository-reviews/profiles'
    | '/repository-reviews/repositories'
    | '/repository-reviews/results'
    | '/threads/$threadId'
    | '/threads/open'
    | '/threads/search'
    | '/accounts/account-router/$index'
    | '/accounts/account-router/new'
    | '/agent/agents/$id'
    | '/agent/agents/new'
    | '/agent/mcp/servers'
    | '/agent/mcp/settings'
    | '/model-evaluations/$evaluationID/report'
    | '/model-evaluations/$id/corpus'
    | '/model-evaluations/$id/edit'
    | '/model-evaluations/$id/languages'
    | '/models/aliases/$name'
    | '/models/aliases/new'
    | '/models/routers/$name'
    | '/models/routers/new'
    | '/threads/open/$threadId'
    | '/agent/agents/$id/activity'
    | '/agent/agents/$id/capabilities'
    | '/agent/agents/$id/edit'
    | '/agent/mcp/servers/$name'
    | '/agent/mcp/servers/new'
    | '/models/aliases/$name/edit'
    | '/models/routers/$name/edit'
    | '/agent/mcp/servers/$name/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/channels'
    | '/accounts'
    | '/agent'
    | '/config'
    | '/development'
    | '/event-sources'
    | '/events'
    | '/launcher-login'
    | '/launcher-setup'
    | '/logs'
    | '/model-evaluations'
    | '/notifications'
    | '/repository-reviews'
    | '/threads'
    | '/agent/agents'
    | '/agent/git-workspaces'
    | '/agent/hub'
    | '/agent/skills'
    | '/agent/tools'
    | '/agent/workflows'
    | '/channels/$name'
    | '/config/raw'
    | '/development/$workspaceID'
    | '/development/new'
    | '/development/repositories'
    | '/development/settings'
    | '/development/workflow-configurations'
    | '/model-evaluations/$id'
    | '/model-evaluations/new'
    | '/models/aliases'
    | '/models/routers'
    | '/notifications/$notificationID'
    | '/repository-reviews/profiles'
    | '/repository-reviews/repositories'
    | '/repository-reviews/results'
    | '/threads/$threadId'
    | '/threads/open'
    | '/threads/search'
    | '/accounts/account-router/$index'
    | '/accounts/account-router/new'
    | '/agent/agents/$id'
    | '/agent/agents/new'
    | '/agent/mcp/servers'
    | '/agent/mcp/settings'
    | '/model-evaluations/$evaluationID/report'
    | '/model-evaluations/$id/corpus'
    | '/model-evaluations/$id/edit'
    | '/model-evaluations/$id/languages'
    | '/models/aliases/$name'
    | '/models/aliases/new'
    | '/models/routers/$name'
    | '/models/routers/new'
    | '/threads/open/$threadId'
    | '/agent/agents/$id/activity'
    | '/agent/agents/$id/capabilities'
    | '/agent/agents/$id/edit'
    | '/agent/mcp/servers/$name'
    | '/agent/mcp/servers/new'
    | '/models/aliases/$name/edit'
    | '/models/routers/$name/edit'
    | '/agent/mcp/servers/$name/edit'
  id:
    | '__root__'
    | '/'
    | '/channels'
    | '/accounts'
    | '/agent'
    | '/config'
    | '/development'
    | '/event-sources'
    | '/events'
    | '/launcher-login'
    | '/launcher-setup'
    | '/logs'
    | '/model-evaluations'
    | '/notifications'
    | '/repository-reviews'
    | '/threads'
    | '/agent/agents'
    | '/agent/git-workspaces'
    | '/agent/hub'
    | '/agent/skills'
    | '/agent/tools'
    | '/agent/workflows'
    | '/channels/$name'
    | '/config/raw'
    | '/development_/$workspaceID'
    | '/development_/new'
    | '/development_/repositories'
    | '/development_/settings'
    | '/development_/workflow-configurations'
    | '/model-evaluations_/$id'
    | '/model-evaluations_/new'
    | '/models_/aliases'
    | '/models_/routers'
    | '/notifications_/$notificationID'
    | '/repository-reviews_/profiles'
    | '/repository-reviews_/repositories'
    | '/repository-reviews_/results'
    | '/threads/$threadId'
    | '/threads/open'
    | '/threads/search'
    | '/accounts/account-router/$index'
    | '/accounts/account-router/new'
    | '/agent/agents_/$id'
    | '/agent/agents_/new'
    | '/agent/mcp_/servers'
    | '/agent/mcp_/settings'
    | '/model-evaluations_/$evaluationID/report'
    | '/model-evaluations_/$id_/corpus'
    | '/model-evaluations_/$id_/edit'
    | '/model-evaluations_/$id_/languages'
    | '/models_/aliases_/$name'
    | '/models_/aliases_/new'
    | '/models_/routers_/$name'
    | '/models_/routers_/new'
    | '/threads/open/$threadId'
    | '/agent/agents_/$id_/activity'
    | '/agent/agents_/$id_/capabilities'
    | '/agent/agents_/$id_/edit'
    | '/agent/mcp_/servers_/$name'
    | '/agent/mcp_/servers_/new'
    | '/models_/aliases_/$name_/edit'
    | '/models_/routers_/$name_/edit'
    | '/agent/mcp_/servers_/$name_/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChannelsRouteRoute: typeof ChannelsRouteRouteWithChildren
  AccountsRoute: typeof AccountsRouteWithChildren
  AgentRoute: typeof AgentRouteWithChildren
  ConfigRoute: typeof ConfigRouteWithChildren
  DevelopmentRoute: typeof DevelopmentRoute
  EventSourcesRoute: typeof EventSourcesRoute
  EventsRoute: typeof EventsRoute
  LauncherLoginRoute: typeof LauncherLoginRoute
  LauncherSetupRoute: typeof LauncherSetupRoute
  LogsRoute: typeof LogsRoute
  ModelEvaluationsRoute: typeof ModelEvaluationsRoute
  NotificationsRoute: typeof NotificationsRoute
  RepositoryReviewsRoute: typeof RepositoryReviewsRoute
  ThreadsRoute: typeof ThreadsRouteWithChildren
  DevelopmentWorkspaceIDRoute: typeof DevelopmentWorkspaceIDRoute
  DevelopmentNewRoute: typeof DevelopmentNewRoute
  DevelopmentRepositoriesRoute: typeof DevelopmentRepositoriesRoute
  DevelopmentSettingsRoute: typeof DevelopmentSettingsRoute
  DevelopmentWorkflowConfigurationsRoute: typeof DevelopmentWorkflowConfigurationsRoute
  ModelEvaluationsIdRoute: typeof ModelEvaluationsIdRoute
  ModelEvaluationsNewRoute: typeof ModelEvaluationsNewRoute
  ModelsAliasesRoute: typeof ModelsAliasesRoute
  ModelsRoutersRoute: typeof ModelsRoutersRoute
  NotificationsNotificationIDRoute: typeof NotificationsNotificationIDRoute
  RepositoryReviewsProfilesRoute: typeof RepositoryReviewsProfilesRoute
  RepositoryReviewsRepositoriesRoute: typeof RepositoryReviewsRepositoriesRoute
  RepositoryReviewsResultsRoute: typeof RepositoryReviewsResultsRoute
  ModelEvaluationsEvaluationIDReportRoute: typeof ModelEvaluationsEvaluationIDReportRoute
  ModelEvaluationsIdCorpusRoute: typeof ModelEvaluationsIdCorpusRoute
  ModelEvaluationsIdEditRoute: typeof ModelEvaluationsIdEditRoute
  ModelEvaluationsIdLanguagesRoute: typeof ModelEvaluationsIdLanguagesRoute
  ModelsAliasesNameRoute: typeof ModelsAliasesNameRoute
  ModelsAliasesNewRoute: typeof ModelsAliasesNewRoute
  ModelsRoutersNameRoute: typeof ModelsRoutersNameRoute
  ModelsRoutersNewRoute: typeof ModelsRoutersNewRoute
  ModelsAliasesNameEditRoute: typeof ModelsAliasesNameEditRoute
  ModelsRoutersNameEditRoute: typeof ModelsRoutersNameEditRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/threads': {
      id: '/threads'
      path: '/threads'
      fullPath: '/threads'
      preLoaderRoute: typeof ThreadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/repository-reviews': {
      id: '/repository-reviews'
      path: '/repository-reviews'
      fullPath: '/repository-reviews'
      preLoaderRoute: typeof RepositoryReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/model-evaluations': {
      id: '/model-evaluations'
      path: '/model-evaluations'
      fullPath: '/model-evaluations'
      preLoaderRoute: typeof ModelEvaluationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logs': {
      id: '/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof LogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/launcher-setup': {
      id: '/launcher-setup'
      path: '/launcher-setup'
      fullPath: '/launcher-setup'
      preLoaderRoute: typeof LauncherSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/launcher-login': {
      id: '/launcher-login'
      path: '/launcher-login'
      fullPath: '/launcher-login'
      preLoaderRoute: typeof LauncherLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/event-sources': {
      id: '/event-sources'
      path: '/event-sources'
      fullPath: '/event-sources'
      preLoaderRoute: typeof EventSourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/development': {
      id: '/development'
      path: '/development'
      fullPath: '/development'
      preLoaderRoute: typeof DevelopmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/config': {
      id: '/config'
      path: '/config'
      fullPath: '/config'
      preLoaderRoute: typeof ConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent': {
      id: '/agent'
      path: '/agent'
      fullPath: '/agent'
      preLoaderRoute: typeof AgentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounts': {
      id: '/accounts'
      path: '/accounts'
      fullPath: '/accounts'
      preLoaderRoute: typeof AccountsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/channels': {
      id: '/channels'
      path: '/channels'
      fullPath: '/channels'
      preLoaderRoute: typeof ChannelsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/threads/search': {
      id: '/threads/search'
      path: '/search'
      fullPath: '/threads/search'
      preLoaderRoute: typeof ThreadsSearchRouteImport
      parentRoute: typeof ThreadsRoute
    }
    '/threads/open': {
      id: '/threads/open'
      path: '/open'
      fullPath: '/threads/open'
      preLoaderRoute: typeof ThreadsOpenRouteImport
      parentRoute: typeof ThreadsRoute
    }
    '/threads/$threadId': {
      id: '/threads/$threadId'
      path: '/$threadId'
      fullPath: '/threads/$threadId'
      preLoaderRoute: typeof ThreadsThreadIdRouteImport
      parentRoute: typeof ThreadsRoute
    }
    '/repository-reviews_/results': {
      id: '/repository-reviews_/results'
      path: '/repository-reviews/results'
      fullPath: '/repository-reviews/results'
      preLoaderRoute: typeof RepositoryReviewsResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/repository-reviews_/repositories': {
      id: '/repository-reviews_/repositories'
      path: '/repository-reviews/repositories'
      fullPath: '/repository-reviews/repositories'
      preLoaderRoute: typeof RepositoryReviewsRepositoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/repository-reviews_/profiles': {
      id: '/repository-reviews_/profiles'
      path: '/repository-reviews/profiles'
      fullPath: '/repository-reviews/profiles'
      preLoaderRoute: typeof RepositoryReviewsProfilesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications_/$notificationID': {
      id: '/notifications_/$notificationID'
      path: '/notifications/$notificationID'
      fullPath: '/notifications/$notificationID'
      preLoaderRoute: typeof NotificationsNotificationIDRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/models_/routers': {
      id: '/models_/routers'
      path: '/models/routers'
      fullPath: '/models/routers'
      preLoaderRoute: typeof ModelsRoutersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/models_/aliases': {
      id: '/models_/aliases'
      path: '/models/aliases'
      fullPath: '/models/aliases'
      preLoaderRoute: typeof ModelsAliasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/model-evaluations_/new': {
      id: '/model-evaluations_/new'
      path: '/model-evaluations/new'
      fullPath: '/model-evaluations/new'
      preLoaderRoute: typeof ModelEvaluationsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/model-evaluations_/$id': {
      id: '/model-evaluations_/$id'
      path: '/model-evaluations/$id'
      fullPath: '/model-evaluations/$id'
      preLoaderRoute: typeof ModelEvaluationsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/development_/workflow-configurations': {
      id: '/development_/workflow-configurations'
      path: '/development/workflow-configurations'
      fullPath: '/development/workflow-configurations'
      preLoaderRoute: typeof DevelopmentWorkflowConfigurationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/development_/settings': {
      id: '/development_/settings'
      path: '/development/settings'
      fullPath: '/development/settings'
      preLoaderRoute: typeof DevelopmentSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/development_/repositories': {
      id: '/development_/repositories'
      path: '/development/repositories'
      fullPath: '/development/repositories'
      preLoaderRoute: typeof DevelopmentRepositoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/development_/new': {
      id: '/development_/new'
      path: '/development/new'
      fullPath: '/development/new'
      preLoaderRoute: typeof DevelopmentNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/development_/$workspaceID': {
      id: '/development_/$workspaceID'
      path: '/development/$workspaceID'
      fullPath: '/development/$workspaceID'
      preLoaderRoute: typeof DevelopmentWorkspaceIDRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/config/raw': {
      id: '/config/raw'
      path: '/raw'
      fullPath: '/config/raw'
      preLoaderRoute: typeof ConfigRawRouteImport
      parentRoute: typeof ConfigRoute
    }
    '/channels/$name': {
      id: '/channels/$name'
      path: '/$name'
      fullPath: '/channels/$name'
      preLoaderRoute: typeof ChannelsNameRouteImport
      parentRoute: typeof ChannelsRouteRoute
    }
    '/agent/workflows': {
      id: '/agent/workflows'
      path: '/workflows'
      fullPath: '/agent/workflows'
      preLoaderRoute: typeof AgentWorkflowsRouteImport
      parentRoute: typeof AgentRoute
    }
    '/agent/tools': {
      id: '/agent/tools'
      path: '/tools'
      fullPath: '/agent/tools'
      preLoaderRoute: typeof AgentToolsRouteImport
      parentRoute: typeof AgentRoute
    }
    '/agent/skills': {
      id: '/agent/skills'
      path: '/skills'
      fullPath: '/agent/skills'
      preLoaderRoute: typeof AgentSkillsRouteImport
      parentRoute: typeof AgentRoute
    }
    '/agent/hub': {
      id: '/agent/hub'
      path: '/hub'
      fullPath: '/agent/hub'
      preLoaderRoute: typeof AgentHubRouteImport
      parentRoute: typeof AgentRoute
    }
    '/agent/git-workspaces': {
      id: '/agent/git-workspaces'
      path: '/git-workspaces'
      fullPath: '/agent/git-workspaces'
      preLoaderRoute: typeof AgentGitWorkspacesRouteImport
      parentRoute: typeof AgentRoute
    }
    '/agent/agents': {
      id: '/agent/agents'
      path: '/agents'
      fullPath: '/agent/agents'
      preLoaderRoute: typeof AgentAgentsRouteImport
      parentRoute: typeof AgentRoute
    }
    '/threads/open/$threadId': {
      id: '/threads/open/$threadId'
      path: '/$threadId'
      fullPath: '/threads/open/$threadId'
      preLoaderRoute: typeof ThreadsOpenThreadIdRouteImport
      parentRoute: typeof ThreadsOpenRoute
    }
    '/models_/routers_/new': {
      id: '/models_/routers_/new'
      path: '/models/routers/new'
      fullPath: '/models/routers/new'
      preLoaderRoute: typeof ModelsRoutersNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/models_/routers_/$name': {
      id: '/models_/routers_/$name'
      path: '/models/routers/$name'
      fullPath: '/models/routers/$name'
      preLoaderRoute: typeof ModelsRoutersNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/models_/aliases_/new': {
      id: '/models_/aliases_/new'
      path: '/models/aliases/new'
      fullPath: '/models/aliases/new'
      preLoaderRoute: typeof ModelsAliasesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/models_/aliases_/$name': {
      id: '/models_/aliases_/$name'
      path: '/models/aliases/$name'
      fullPath: '/models/aliases/$name'
      preLoaderRoute: typeof ModelsAliasesNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/model-evaluations_/$id_/languages': {
      id: '/model-evaluations_/$id_/languages'
      path: '/model-evaluations/$id/languages'
      fullPath: '/model-evaluations/$id/languages'
      preLoaderRoute: typeof ModelEvaluationsIdLanguagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/model-evaluations_/$id_/edit': {
      id: '/model-evaluations_/$id_/edit'
      path: '/model-evaluations/$id/edit'
      fullPath: '/model-evaluations/$id/edit'
      preLoaderRoute: typeof ModelEvaluationsIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/model-evaluations_/$id_/corpus': {
      id: '/model-evaluations_/$id_/corpus'
      path: '/model-evaluations/$id/corpus'
      fullPath: '/model-evaluations/$id/corpus'
      preLoaderRoute: typeof ModelEvaluationsIdCorpusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/model-evaluations_/$evaluationID/report': {
      id: '/model-evaluations_/$evaluationID/report'
      path: '/model-evaluations/$evaluationID/report'
      fullPath: '/model-evaluations/$evaluationID/report'
      preLoaderRoute: typeof ModelEvaluationsEvaluationIDReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent/mcp_/settings': {
      id: '/agent/mcp_/settings'
      path: '/mcp/settings'
      fullPath: '/agent/mcp/settings'
      preLoaderRoute: typeof AgentMcpSettingsRouteImport
      parentRoute: typeof AgentRoute
    }
    '/agent/mcp_/servers': {
      id: '/agent/mcp_/servers'
      path: '/mcp/servers'
      fullPath: '/agent/mcp/servers'
      preLoaderRoute: typeof AgentMcpServersRouteImport
      parentRoute: typeof AgentRoute
    }
    '/agent/agents_/new': {
      id: '/agent/agents_/new'
      path: '/agents/new'
      fullPath: '/agent/agents/new'
      preLoaderRoute: typeof AgentAgentsNewRouteImport
      parentRoute: typeof AgentRoute
    }
    '/agent/agents_/$id': {
      id: '/agent/agents_/$id'
      path: '/agents/$id'
      fullPath: '/agent/agents/$id'
      preLoaderRoute: typeof AgentAgentsIdRouteImport
      parentRoute: typeof AgentRoute
    }
    '/accounts/account-router/new': {
      id: '/accounts/account-router/new'
      path: '/account-router/new'
      fullPath: '/accounts/account-router/new'
      preLoaderRoute: typeof AccountsAccountRouterNewRouteImport
      parentRoute: typeof AccountsRoute
    }
    '/accounts/account-router/$index': {
      id: '/accounts/account-router/$index'
      path: '/account-router/$index'
      fullPath: '/accounts/account-router/$index'
      preLoaderRoute: typeof AccountsAccountRouterIndexRouteImport
      parentRoute: typeof AccountsRoute
    }
    '/models_/routers_/$name_/edit': {
      id: '/models_/routers_/$name_/edit'
      path: '/models/routers/$name/edit'
      fullPath: '/models/routers/$name/edit'
      preLoaderRoute: typeof ModelsRoutersNameEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/models_/aliases_/$name_/edit': {
      id: '/models_/aliases_/$name_/edit'
      path: '/models/aliases/$name/edit'
      fullPath: '/models/aliases/$name/edit'
      preLoaderRoute: typeof ModelsAliasesNameEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent/mcp_/servers_/new': {
      id: '/agent/mcp_/servers_/new'
      path: '/mcp/servers/new'
      fullPath: '/agent/mcp/servers/new'
      preLoaderRoute: typeof AgentMcpServersNewRouteImport
      parentRoute: typeof AgentRoute
    }
    '/agent/mcp_/servers_/$name': {
      id: '/agent/mcp_/servers_/$name'
      path: '/mcp/servers/$name'
      fullPath: '/agent/mcp/servers/$name'
      preLoaderRoute: typeof AgentMcpServersNameRouteImport
      parentRoute: typeof AgentRoute
    }
    '/agent/agents_/$id_/edit': {
      id: '/agent/agents_/$id_/edit'
      path: '/agents/$id/edit'
      fullPath: '/agent/agents/$id/edit'
      preLoaderRoute: typeof AgentAgentsIdEditRouteImport
      parentRoute: typeof AgentRoute
    }
    '/agent/agents_/$id_/capabilities': {
      id: '/agent/agents_/$id_/capabilities'
      path: '/agents/$id/capabilities'
      fullPath: '/agent/agents/$id/capabilities'
      preLoaderRoute: typeof AgentAgentsIdCapabilitiesRouteImport
      parentRoute: typeof AgentRoute
    }
    '/agent/agents_/$id_/activity': {
      id: '/agent/agents_/$id_/activity'
      path: '/agents/$id/activity'
      fullPath: '/agent/agents/$id/activity'
      preLoaderRoute: typeof AgentAgentsIdActivityRouteImport
      parentRoute: typeof AgentRoute
    }
    '/agent/mcp_/servers_/$name_/edit': {
      id: '/agent/mcp_/servers_/$name_/edit'
      path: '/mcp/servers/$name/edit'
      fullPath: '/agent/mcp/servers/$name/edit'
      preLoaderRoute: typeof AgentMcpServersNameEditRouteImport
      parentRoute: typeof AgentRoute
    }
  }
}

interface ChannelsRouteRouteChildren {
  ChannelsNameRoute: typeof ChannelsNameRoute
}

const ChannelsRouteRouteChildren: ChannelsRouteRouteChildren = {
  ChannelsNameRoute: ChannelsNameRoute,
}

const ChannelsRouteRouteWithChildren = ChannelsRouteRoute._addFileChildren(
  ChannelsRouteRouteChildren,
)

interface AccountsRouteChildren {
  AccountsAccountRouterIndexRoute: typeof AccountsAccountRouterIndexRoute
  AccountsAccountRouterNewRoute: typeof AccountsAccountRouterNewRoute
}

const AccountsRouteChildren: AccountsRouteChildren = {
  AccountsAccountRouterIndexRoute: AccountsAccountRouterIndexRoute,
  AccountsAccountRouterNewRoute: AccountsAccountRouterNewRoute,
}

const AccountsRouteWithChildren = AccountsRoute._addFileChildren(
  AccountsRouteChildren,
)

interface AgentRouteChildren {
  AgentAgentsRoute: typeof AgentAgentsRoute
  AgentGitWorkspacesRoute: typeof AgentGitWorkspacesRoute
  AgentHubRoute: typeof AgentHubRoute
  AgentSkillsRoute: typeof AgentSkillsRoute
  AgentToolsRoute: typeof AgentToolsRoute
  AgentWorkflowsRoute: typeof AgentWorkflowsRoute
  AgentAgentsIdRoute: typeof AgentAgentsIdRoute
  AgentAgentsNewRoute: typeof AgentAgentsNewRoute
  AgentMcpServersRoute: typeof AgentMcpServersRoute
  AgentMcpSettingsRoute: typeof AgentMcpSettingsRoute
  AgentAgentsIdActivityRoute: typeof AgentAgentsIdActivityRoute
  AgentAgentsIdCapabilitiesRoute: typeof AgentAgentsIdCapabilitiesRoute
  AgentAgentsIdEditRoute: typeof AgentAgentsIdEditRoute
  AgentMcpServersNameRoute: typeof AgentMcpServersNameRoute
  AgentMcpServersNewRoute: typeof AgentMcpServersNewRoute
  AgentMcpServersNameEditRoute: typeof AgentMcpServersNameEditRoute
}

const AgentRouteChildren: AgentRouteChildren = {
  AgentAgentsRoute: AgentAgentsRoute,
  AgentGitWorkspacesRoute: AgentGitWorkspacesRoute,
  AgentHubRoute: AgentHubRoute,
  AgentSkillsRoute: AgentSkillsRoute,
  AgentToolsRoute: AgentToolsRoute,
  AgentWorkflowsRoute: AgentWorkflowsRoute,
  AgentAgentsIdRoute: AgentAgentsIdRoute,
  AgentAgentsNewRoute: AgentAgentsNewRoute,
  AgentMcpServersRoute: AgentMcpServersRoute,
  AgentMcpSettingsRoute: AgentMcpSettingsRoute,
  AgentAgentsIdActivityRoute: AgentAgentsIdActivityRoute,
  AgentAgentsIdCapabilitiesRoute: AgentAgentsIdCapabilitiesRoute,
  AgentAgentsIdEditRoute: AgentAgentsIdEditRoute,
  AgentMcpServersNameRoute: AgentMcpServersNameRoute,
  AgentMcpServersNewRoute: AgentMcpServersNewRoute,
  AgentMcpServersNameEditRoute: AgentMcpServersNameEditRoute,
}

const AgentRouteWithChildren = AgentRoute._addFileChildren(AgentRouteChildren)

interface ConfigRouteChildren {
  ConfigRawRoute: typeof ConfigRawRoute
}

const ConfigRouteChildren: ConfigRouteChildren = {
  ConfigRawRoute: ConfigRawRoute,
}

const ConfigRouteWithChildren =
  ConfigRoute._addFileChildren(ConfigRouteChildren)

interface ThreadsOpenRouteChildren {
  ThreadsOpenThreadIdRoute: typeof ThreadsOpenThreadIdRoute
}

const ThreadsOpenRouteChildren: ThreadsOpenRouteChildren = {
  ThreadsOpenThreadIdRoute: ThreadsOpenThreadIdRoute,
}

const ThreadsOpenRouteWithChildren = ThreadsOpenRoute._addFileChildren(
  ThreadsOpenRouteChildren,
)

interface ThreadsRouteChildren {
  ThreadsThreadIdRoute: typeof ThreadsThreadIdRoute
  ThreadsOpenRoute: typeof ThreadsOpenRouteWithChildren
  ThreadsSearchRoute: typeof ThreadsSearchRoute
}

const ThreadsRouteChildren: ThreadsRouteChildren = {
  ThreadsThreadIdRoute: ThreadsThreadIdRoute,
  ThreadsOpenRoute: ThreadsOpenRouteWithChildren,
  ThreadsSearchRoute: ThreadsSearchRoute,
}

const ThreadsRouteWithChildren =
  ThreadsRoute._addFileChildren(ThreadsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChannelsRouteRoute: ChannelsRouteRouteWithChildren,
  AccountsRoute: AccountsRouteWithChildren,
  AgentRoute: AgentRouteWithChildren,
  ConfigRoute: ConfigRouteWithChildren,
  DevelopmentRoute: DevelopmentRoute,
  EventSourcesRoute: EventSourcesRoute,
  EventsRoute: EventsRoute,
  LauncherLoginRoute: LauncherLoginRoute,
  LauncherSetupRoute: LauncherSetupRoute,
  LogsRoute: LogsRoute,
  ModelEvaluationsRoute: ModelEvaluationsRoute,
  NotificationsRoute: NotificationsRoute,
  RepositoryReviewsRoute: RepositoryReviewsRoute,
  ThreadsRoute: ThreadsRouteWithChildren,
  DevelopmentWorkspaceIDRoute: DevelopmentWorkspaceIDRoute,
  DevelopmentNewRoute: DevelopmentNewRoute,
  DevelopmentRepositoriesRoute: DevelopmentRepositoriesRoute,
  DevelopmentSettingsRoute: DevelopmentSettingsRoute,
  DevelopmentWorkflowConfigurationsRoute:
    DevelopmentWorkflowConfigurationsRoute,
  ModelEvaluationsIdRoute: ModelEvaluationsIdRoute,
  ModelEvaluationsNewRoute: ModelEvaluationsNewRoute,
  ModelsAliasesRoute: ModelsAliasesRoute,
  ModelsRoutersRoute: ModelsRoutersRoute,
  NotificationsNotificationIDRoute: NotificationsNotificationIDRoute,
  RepositoryReviewsProfilesRoute: RepositoryReviewsProfilesRoute,
  RepositoryReviewsRepositoriesRoute: RepositoryReviewsRepositoriesRoute,
  RepositoryReviewsResultsRoute: RepositoryReviewsResultsRoute,
  ModelEvaluationsEvaluationIDReportRoute:
    ModelEvaluationsEvaluationIDReportRoute,
  ModelEvaluationsIdCorpusRoute: ModelEvaluationsIdCorpusRoute,
  ModelEvaluationsIdEditRoute: ModelEvaluationsIdEditRoute,
  ModelEvaluationsIdLanguagesRoute: ModelEvaluationsIdLanguagesRoute,
  ModelsAliasesNameRoute: ModelsAliasesNameRoute,
  ModelsAliasesNewRoute: ModelsAliasesNewRoute,
  ModelsRoutersNameRoute: ModelsRoutersNameRoute,
  ModelsRoutersNewRoute: ModelsRoutersNewRoute,
  ModelsAliasesNameEditRoute: ModelsAliasesNameEditRoute,
  ModelsRoutersNameEditRoute: ModelsRoutersNameEditRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
