/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ThreadsRouteImport } from './routes/threads'
import { Route as RepositoryReviewsRouteImport } from './routes/repository-reviews'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as ModelEvaluationsRouteImport } from './routes/model-evaluations'
import { Route as LogsRouteImport } from './routes/logs'
import { Route as LauncherSetupRouteImport } from './routes/launcher-setup'
import { Route as LauncherLoginRouteImport } from './routes/launcher-login'
import { Route as EventsRouteImport } from './routes/events'
import { Route as EventSourcesRouteImport } from './routes/event-sources'
import { Route as DevelopmentRouteImport } from './routes/development'
import { Route as ConfigRouteImport } from './routes/config'
import { Route as AgentRouteImport } from './routes/agent'
import { Route as AccountsRouteImport } from './routes/accounts'
import { Route as ChannelsRouteRouteImport } from './routes/channels/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ThreadsSearchRouteImport } from './routes/threads.search'
import { Route as ThreadsOpenRouteImport } from './routes/threads.open'
import { Route as ThreadsThreadIdRouteImport } from './routes/threads.$threadId'
import { Route as RepositoryReviewsResultsRouteImport } from './routes/repository-reviews_.results'
import { Route as RepositoryReviewsRepositoriesRouteImport } from './routes/repository-reviews_.repositories'
import { Route as RepositoryReviewsProfilesRouteImport } from './routes/repository-reviews_.profiles'
import { Route as RepositoryReviewsIdRouteImport } from './routes/repository-reviews_.$id'
import { Route as NotificationsNotificationIDRouteImport } from './routes/notifications_.$notificationID'
import { Route as ModelsRoutersRouteImport } from './routes/models_.routers'
import { Route as ModelsAliasesRouteImport } from './routes/models_.aliases'
import { Route as ModelEvaluationsNewRouteImport } from './routes/model-evaluations_.new'
import { Route as ModelEvaluationsIdRouteImport } from './routes/model-evaluations_.$id'
import { Route as EventSourcesSettingsRouteImport } from './routes/event-sources_.settings'
import { Route as EventSourcesNewRouteImport } from './routes/event-sources_.new'
import { Route as EventSourcesIdRouteImport } from './routes/event-sources_.$id'
import { Route as DevelopmentWorkflowConfigurationsRouteImport } from './routes/development_.workflow-configurations'
import { Route as DevelopmentSettingsRouteImport } from './routes/development_.settings'
import { Route as DevelopmentRepositoriesRouteImport } from './routes/development_.repositories'
import { Route as DevelopmentNewRouteImport } from './routes/development_.new'
import { Route as DevelopmentWorkspaceIDRouteImport } from './routes/development_.$workspaceID'
import { Route as ConfigRawRouteImport } from './routes/config.raw'
import { Route as ChannelsNameRouteImport } from './routes/channels/$name'
import { Route as AgentWorkflowsRouteImport } from './routes/agent/workflows'
import { Route as AgentToolsRouteImport } from './routes/agent/tools'
import { Route as AgentSkillsRouteImport } from './routes/agent/skills'
import { Route as AgentHubRouteImport } from './routes/agent/hub'
import { Route as AgentGitWorkspacesRouteImport } from './routes/agent/git-workspaces'
import { Route as AgentAgentsRouteImport } from './routes/agent/agents'
import { Route as AccountsRoutersRouteImport } from './routes/accounts_.routers'
import { Route as AccountsNewRouteImport } from './routes/accounts_.new'
import { Route as AccountsIdRouteImport } from './routes/accounts_.$id'
import { Route as ThreadsOpenThreadIdRouteImport } from './routes/threads.open.$threadId'
import { Route as RepositoryReviewsRepositoriesNewRouteImport } from './routes/repository-reviews_.repositories_.new'
import { Route as RepositoryReviewsRepositoriesIdRouteImport } from './routes/repository-reviews_.repositories_.$id'
import { Route as RepositoryReviewsProfilesNewRouteImport } from './routes/repository-reviews_.profiles_.new'
import { Route as RepositoryReviewsProfilesProfileIDRouteImport } from './routes/repository-reviews_.profiles_.$profileID'
import { Route as RepositoryReviewsIdReportRouteImport } from './routes/repository-reviews_.$id_.report'
import { Route as RepositoryReviewsIdIssuesRouteImport } from './routes/repository-reviews_.$id_.issues'
import { Route as RepositoryReviewsIdFindingsRouteImport } from './routes/repository-reviews_.$id_.findings'
import { Route as ModelsRoutersNewRouteImport } from './routes/models_.routers_.new'
import { Route as ModelsRoutersNameRouteImport } from './routes/models_.routers_.$name'
import { Route as ModelsAliasesNewRouteImport } from './routes/models_.aliases_.new'
import { Route as ModelsAliasesNameRouteImport } from './routes/models_.aliases_.$name'
import { Route as ModelEvaluationsIdLanguagesRouteImport } from './routes/model-evaluations_.$id_.languages'
import { Route as ModelEvaluationsIdEditRouteImport } from './routes/model-evaluations_.$id_.edit'
import { Route as ModelEvaluationsIdCorpusRouteImport } from './routes/model-evaluations_.$id_.corpus'
import { Route as ModelEvaluationsEvaluationIDReportRouteImport } from './routes/model-evaluations_.$evaluationID.report'
import { Route as EventSourcesIdEditRouteImport } from './routes/event-sources_.$id_.edit'
import { Route as AgentWorkflowsSettingsRouteImport } from './routes/agent/workflows_.settings'
import { Route as AgentWorkflowsRunsRouteImport } from './routes/agent/workflows_.runs'
import { Route as AgentWorkflowsNewRouteImport } from './routes/agent/workflows_.new'
import { Route as AgentWorkflowsIdRouteImport } from './routes/agent/workflows_.$id'
import { Route as AgentToolsIdRouteImport } from './routes/agent/tools_.$id'
import { Route as AgentSkillsNewRouteImport } from './routes/agent/skills_.new'
import { Route as AgentSkillsIdRouteImport } from './routes/agent/skills_.$id'
import { Route as AgentMcpSettingsRouteImport } from './routes/agent/mcp_.settings'
import { Route as AgentMcpServersRouteImport } from './routes/agent/mcp_.servers'
import { Route as AgentGitWorkspacesSettingsRouteImport } from './routes/agent/git-workspaces_.settings'
import { Route as AgentGitWorkspacesHistoryRouteImport } from './routes/agent/git-workspaces_.history'
import { Route as AgentGitWorkspacesIdRouteImport } from './routes/agent/git-workspaces_.$id'
import { Route as AgentAgentsNewRouteImport } from './routes/agent/agents_.new'
import { Route as AgentAgentsIdRouteImport } from './routes/agent/agents_.$id'
import { Route as AccountsRoutersNewRouteImport } from './routes/accounts_.routers_.new'
import { Route as AccountsRoutersIdRouteImport } from './routes/accounts_.routers_.$id'
import { Route as AccountsIdEditRouteImport } from './routes/accounts_.$id_.edit'
import { Route as RepositoryReviewsRepositoriesIdFindingsRouteImport } from './routes/repository-reviews_.repositories_.$id_.findings'
import { Route as RepositoryReviewsRepositoriesIdEditRouteImport } from './routes/repository-reviews_.repositories_.$id_.edit'
import { Route as RepositoryReviewsProfilesProfileIDEditRouteImport } from './routes/repository-reviews_.profiles_.$profileID_.edit'
import { Route as RepositoryReviewsIdIssuesDraftIdRouteImport } from './routes/repository-reviews_.$id_.issues_.$draftId'
import { Route as RepositoryReviewsIdFindingsFindingIdRouteImport } from './routes/repository-reviews_.$id_.findings_.$findingId'
import { Route as ModelsRoutersNameEditRouteImport } from './routes/models_.routers_.$name_.edit'
import { Route as ModelsAliasesNameEditRouteImport } from './routes/models_.aliases_.$name_.edit'
import { Route as AgentWorkflowsRunsIdRouteImport } from './routes/agent/workflows_.runs_.$id'
import { Route as AgentWorkflowsIdEditRouteImport } from './routes/agent/workflows_.$id_.edit'
import { Route as AgentToolsSettingsAdaptationRouteImport } from './routes/agent/tools_.settings_.adaptation'
import { Route as AgentToolsIdEditRouteImport } from './routes/agent/tools_.$id_.edit'
import { Route as AgentMcpServersNewRouteImport } from './routes/agent/mcp_.servers_.new'
import { Route as AgentMcpServersNameRouteImport } from './routes/agent/mcp_.servers_.$name'
import { Route as AgentAgentsIdEditRouteImport } from './routes/agent/agents_.$id_.edit'
import { Route as AgentAgentsIdCapabilitiesRouteImport } from './routes/agent/agents_.$id_.capabilities'
import { Route as AgentAgentsIdActivityRouteImport } from './routes/agent/agents_.$id_.activity'
import { Route as AccountsRoutersIdEditRouteImport } from './routes/accounts_.routers_.$id_.edit'
import { Route as RepositoryReviewsRepositoriesIdFindingsFindingIdRouteImport } from './routes/repository-reviews_.repositories_.$id_.findings_.$findingId'
import { Route as RepositoryReviewsIdFindingsFindingIdLinkIssueRouteImport } from './routes/repository-reviews_.$id_.findings_.$findingId_.link-issue'
import { Route as AgentMcpServersNameEditRouteImport } from './routes/agent/mcp_.servers_.$name_.edit'
import { Route as RepositoryReviewsRepositoriesIdFindingsFindingIdLinkIssueRouteImport } from './routes/repository-reviews_.repositories_.$id_.findings_.$findingId_.link-issue'

const ThreadsRoute = ThreadsRouteImport.update({
  id: '/threads',
  path: '/threads',
  getParentRoute: () => rootRouteImport,
} as any)
const RepositoryReviewsRoute = RepositoryReviewsRouteImport.update({
  id: '/repository-reviews',
  path: '/repository-reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const ModelEvaluationsRoute = ModelEvaluationsRouteImport.update({
  id: '/model-evaluations',
  path: '/model-evaluations',
  getParentRoute: () => rootRouteImport,
} as any)
const LogsRoute = LogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => rootRouteImport,
} as any)
const LauncherSetupRoute = LauncherSetupRouteImport.update({
  id: '/launcher-setup',
  path: '/launcher-setup',
  getParentRoute: () => rootRouteImport,
} as any)
const LauncherLoginRoute = LauncherLoginRouteImport.update({
  id: '/launcher-login',
  path: '/launcher-login',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const EventSourcesRoute = EventSourcesRouteImport.update({
  id: '/event-sources',
  path: '/event-sources',
  getParentRoute: () => rootRouteImport,
} as any)
const DevelopmentRoute = DevelopmentRouteImport.update({
  id: '/development',
  path: '/development',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfigRoute = ConfigRouteImport.update({
  id: '/config',
  path: '/config',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentRoute = AgentRouteImport.update({
  id: '/agent',
  path: '/agent',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountsRoute = AccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => rootRouteImport,
} as any)
const ChannelsRouteRoute = ChannelsRouteRouteImport.update({
  id: '/channels',
  path: '/channels',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ThreadsSearchRoute = ThreadsSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => ThreadsRoute,
} as any)
const ThreadsOpenRoute = ThreadsOpenRouteImport.update({
  id: '/open',
  path: '/open',
  getParentRoute: () => ThreadsRoute,
} as any)
const ThreadsThreadIdRoute = ThreadsThreadIdRouteImport.update({
  id: '/$threadId',
  path: '/$threadId',
  getParentRoute: () => ThreadsRoute,
} as any)
const RepositoryReviewsResultsRoute =
  RepositoryReviewsResultsRouteImport.update({
    id: '/repository-reviews_/results',
    path: '/repository-reviews/results',
    getParentRoute: () => rootRouteImport,
  } as any)
const RepositoryReviewsRepositoriesRoute =
  RepositoryReviewsRepositoriesRouteImport.update({
    id: '/repository-reviews_/repositories',
    path: '/repository-reviews/repositories',
    getParentRoute: () => rootRouteImport,
  } as any)
const RepositoryReviewsProfilesRoute =
  RepositoryReviewsProfilesRouteImport.update({
    id: '/repository-reviews_/profiles',
    path: '/repository-reviews/profiles',
    getParentRoute: () => rootRouteImport,
  } as any)
const RepositoryReviewsIdRoute = RepositoryReviewsIdRouteImport.update({
  id: '/repository-reviews_/$id',
  path: '/repository-reviews/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsNotificationIDRoute =
  NotificationsNotificationIDRouteImport.update({
    id: '/notifications_/$notificationID',
    path: '/notifications/$notificationID',
    getParentRoute: () => rootRouteImport,
  } as any)
const ModelsRoutersRoute = ModelsRoutersRouteImport.update({
  id: '/models_/routers',
  path: '/models/routers',
  getParentRoute: () => rootRouteImport,
} as any)
const ModelsAliasesRoute = ModelsAliasesRouteImport.update({
  id: '/models_/aliases',
  path: '/models/aliases',
  getParentRoute: () => rootRouteImport,
} as any)
const ModelEvaluationsNewRoute = ModelEvaluationsNewRouteImport.update({
  id: '/model-evaluations_/new',
  path: '/model-evaluations/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ModelEvaluationsIdRoute = ModelEvaluationsIdRouteImport.update({
  id: '/model-evaluations_/$id',
  path: '/model-evaluations/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const EventSourcesSettingsRoute = EventSourcesSettingsRouteImport.update({
  id: '/event-sources_/settings',
  path: '/event-sources/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const EventSourcesNewRoute = EventSourcesNewRouteImport.update({
  id: '/event-sources_/new',
  path: '/event-sources/new',
  getParentRoute: () => rootRouteImport,
} as any)
const EventSourcesIdRoute = EventSourcesIdRouteImport.update({
  id: '/event-sources_/$id',
  path: '/event-sources/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DevelopmentWorkflowConfigurationsRoute =
  DevelopmentWorkflowConfigurationsRouteImport.update({
    id: '/development_/workflow-configurations',
    path: '/development/workflow-configurations',
    getParentRoute: () => rootRouteImport,
  } as any)
const DevelopmentSettingsRoute = DevelopmentSettingsRouteImport.update({
  id: '/development_/settings',
  path: '/development/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const DevelopmentRepositoriesRoute = DevelopmentRepositoriesRouteImport.update({
  id: '/development_/repositories',
  path: '/development/repositories',
  getParentRoute: () => rootRouteImport,
} as any)
const DevelopmentNewRoute = DevelopmentNewRouteImport.update({
  id: '/development_/new',
  path: '/development/new',
  getParentRoute: () => rootRouteImport,
} as any)
const DevelopmentWorkspaceIDRoute = DevelopmentWorkspaceIDRouteImport.update({
  id: '/development_/$workspaceID',
  path: '/development/$workspaceID',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfigRawRoute = ConfigRawRouteImport.update({
  id: '/raw',
  path: '/raw',
  getParentRoute: () => ConfigRoute,
} as any)
const ChannelsNameRoute = ChannelsNameRouteImport.update({
  id: '/$name',
  path: '/$name',
  getParentRoute: () => ChannelsRouteRoute,
} as any)
const AgentWorkflowsRoute = AgentWorkflowsRouteImport.update({
  id: '/workflows',
  path: '/workflows',
  getParentRoute: () => AgentRoute,
} as any)
const AgentToolsRoute = AgentToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => AgentRoute,
} as any)
const AgentSkillsRoute = AgentSkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => AgentRoute,
} as any)
const AgentHubRoute = AgentHubRouteImport.update({
  id: '/hub',
  path: '/hub',
  getParentRoute: () => AgentRoute,
} as any)
const AgentGitWorkspacesRoute = AgentGitWorkspacesRouteImport.update({
  id: '/git-workspaces',
  path: '/git-workspaces',
  getParentRoute: () => AgentRoute,
} as any)
const AgentAgentsRoute = AgentAgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => AgentRoute,
} as any)
const AccountsRoutersRoute = AccountsRoutersRouteImport.update({
  id: '/accounts_/routers',
  path: '/accounts/routers',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountsNewRoute = AccountsNewRouteImport.update({
  id: '/accounts_/new',
  path: '/accounts/new',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountsIdRoute = AccountsIdRouteImport.update({
  id: '/accounts_/$id',
  path: '/accounts/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ThreadsOpenThreadIdRoute = ThreadsOpenThreadIdRouteImport.update({
  id: '/$threadId',
  path: '/$threadId',
  getParentRoute: () => ThreadsOpenRoute,
} as any)
const RepositoryReviewsRepositoriesNewRoute =
  RepositoryReviewsRepositoriesNewRouteImport.update({
    id: '/repository-reviews_/repositories_/new',
    path: '/repository-reviews/repositories/new',
    getParentRoute: () => rootRouteImport,
  } as any)
const RepositoryReviewsRepositoriesIdRoute =
  RepositoryReviewsRepositoriesIdRouteImport.update({
    id: '/repository-reviews_/repositories_/$id',
    path: '/repository-reviews/repositories/$id',
    getParentRoute: () => rootRouteImport,
  } as any)
const RepositoryReviewsProfilesNewRoute =
  RepositoryReviewsProfilesNewRouteImport.update({
    id: '/repository-reviews_/profiles_/new',
    path: '/repository-reviews/profiles/new',
    getParentRoute: () => rootRouteImport,
  } as any)
const RepositoryReviewsProfilesProfileIDRoute =
  RepositoryReviewsProfilesProfileIDRouteImport.update({
    id: '/repository-reviews_/profiles_/$profileID',
    path: '/repository-reviews/profiles/$profileID',
    getParentRoute: () => rootRouteImport,
  } as any)
const RepositoryReviewsIdReportRoute =
  RepositoryReviewsIdReportRouteImport.update({
    id: '/repository-reviews_/$id_/report',
    path: '/repository-reviews/$id/report',
    getParentRoute: () => rootRouteImport,
  } as any)
const RepositoryReviewsIdIssuesRoute =
  RepositoryReviewsIdIssuesRouteImport.update({
    id: '/repository-reviews_/$id_/issues',
    path: '/repository-reviews/$id/issues',
    getParentRoute: () => rootRouteImport,
  } as any)
const RepositoryReviewsIdFindingsRoute =
  RepositoryReviewsIdFindingsRouteImport.update({
    id: '/repository-reviews_/$id_/findings',
    path: '/repository-reviews/$id/findings',
    getParentRoute: () => rootRouteImport,
  } as any)
const ModelsRoutersNewRoute = ModelsRoutersNewRouteImport.update({
  id: '/models_/routers_/new',
  path: '/models/routers/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ModelsRoutersNameRoute = ModelsRoutersNameRouteImport.update({
  id: '/models_/routers_/$name',
  path: '/models/routers/$name',
  getParentRoute: () => rootRouteImport,
} as any)
const ModelsAliasesNewRoute = ModelsAliasesNewRouteImport.update({
  id: '/models_/aliases_/new',
  path: '/models/aliases/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ModelsAliasesNameRoute = ModelsAliasesNameRouteImport.update({
  id: '/models_/aliases_/$name',
  path: '/models/aliases/$name',
  getParentRoute: () => rootRouteImport,
} as any)
const ModelEvaluationsIdLanguagesRoute =
  ModelEvaluationsIdLanguagesRouteImport.update({
    id: '/model-evaluations_/$id_/languages',
    path: '/model-evaluations/$id/languages',
    getParentRoute: () => rootRouteImport,
  } as any)
const ModelEvaluationsIdEditRoute = ModelEvaluationsIdEditRouteImport.update({
  id: '/model-evaluations_/$id_/edit',
  path: '/model-evaluations/$id/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const ModelEvaluationsIdCorpusRoute =
  ModelEvaluationsIdCorpusRouteImport.update({
    id: '/model-evaluations_/$id_/corpus',
    path: '/model-evaluations/$id/corpus',
    getParentRoute: () => rootRouteImport,
  } as any)
const ModelEvaluationsEvaluationIDReportRoute =
  ModelEvaluationsEvaluationIDReportRouteImport.update({
    id: '/model-evaluations_/$evaluationID/report',
    path: '/model-evaluations/$evaluationID/report',
    getParentRoute: () => rootRouteImport,
  } as any)
const EventSourcesIdEditRoute = EventSourcesIdEditRouteImport.update({
  id: '/event-sources_/$id_/edit',
  path: '/event-sources/$id/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentWorkflowsSettingsRoute = AgentWorkflowsSettingsRouteImport.update({
  id: '/workflows_/settings',
  path: '/workflows/settings',
  getParentRoute: () => AgentRoute,
} as any)
const AgentWorkflowsRunsRoute = AgentWorkflowsRunsRouteImport.update({
  id: '/workflows_/runs',
  path: '/workflows/runs',
  getParentRoute: () => AgentRoute,
} as any)
const AgentWorkflowsNewRoute = AgentWorkflowsNewRouteImport.update({
  id: '/workflows_/new',
  path: '/workflows/new',
  getParentRoute: () => AgentRoute,
} as any)
const AgentWorkflowsIdRoute = AgentWorkflowsIdRouteImport.update({
  id: '/workflows_/$id',
  path: '/workflows/$id',
  getParentRoute: () => AgentRoute,
} as any)
const AgentToolsIdRoute = AgentToolsIdRouteImport.update({
  id: '/tools_/$id',
  path: '/tools/$id',
  getParentRoute: () => AgentRoute,
} as any)
const AgentSkillsNewRoute = AgentSkillsNewRouteImport.update({
  id: '/skills_/new',
  path: '/skills/new',
  getParentRoute: () => AgentRoute,
} as any)
const AgentSkillsIdRoute = AgentSkillsIdRouteImport.update({
  id: '/skills_/$id',
  path: '/skills/$id',
  getParentRoute: () => AgentRoute,
} as any)
const AgentMcpSettingsRoute = AgentMcpSettingsRouteImport.update({
  id: '/mcp_/settings',
  path: '/mcp/settings',
  getParentRoute: () => AgentRoute,
} as any)
const AgentMcpServersRoute = AgentMcpServersRouteImport.update({
  id: '/mcp_/servers',
  path: '/mcp/servers',
  getParentRoute: () => AgentRoute,
} as any)
const AgentGitWorkspacesSettingsRoute =
  AgentGitWorkspacesSettingsRouteImport.update({
    id: '/git-workspaces_/settings',
    path: '/git-workspaces/settings',
    getParentRoute: () => AgentRoute,
  } as any)
const AgentGitWorkspacesHistoryRoute =
  AgentGitWorkspacesHistoryRouteImport.update({
    id: '/git-workspaces_/history',
    path: '/git-workspaces/history',
    getParentRoute: () => AgentRoute,
  } as any)
const AgentGitWorkspacesIdRoute = AgentGitWorkspacesIdRouteImport.update({
  id: '/git-workspaces_/$id',
  path: '/git-workspaces/$id',
  getParentRoute: () => AgentRoute,
} as any)
const AgentAgentsNewRoute = AgentAgentsNewRouteImport.update({
  id: '/agents_/new',
  path: '/agents/new',
  getParentRoute: () => AgentRoute,
} as any)
const AgentAgentsIdRoute = AgentAgentsIdRouteImport.update({
  id: '/agents_/$id',
  path: '/agents/$id',
  getParentRoute: () => AgentRoute,
} as any)
const AccountsRoutersNewRoute = AccountsRoutersNewRouteImport.update({
  id: '/accounts_/routers_/new',
  path: '/accounts/routers/new',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountsRoutersIdRoute = AccountsRoutersIdRouteImport.update({
  id: '/accounts_/routers_/$id',
  path: '/accounts/routers/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountsIdEditRoute = AccountsIdEditRouteImport.update({
  id: '/accounts_/$id_/edit',
  path: '/accounts/$id/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const RepositoryReviewsRepositoriesIdFindingsRoute =
  RepositoryReviewsRepositoriesIdFindingsRouteImport.update({
    id: '/repository-reviews_/repositories_/$id_/findings',
    path: '/repository-reviews/repositories/$id/findings',
    getParentRoute: () => rootRouteImport,
  } as any)
const RepositoryReviewsRepositoriesIdEditRoute =
  RepositoryReviewsRepositoriesIdEditRouteImport.update({
    id: '/repository-reviews_/repositories_/$id_/edit',
    path: '/repository-reviews/repositories/$id/edit',
    getParentRoute: () => rootRouteImport,
  } as any)
const RepositoryReviewsProfilesProfileIDEditRoute =
  RepositoryReviewsProfilesProfileIDEditRouteImport.update({
    id: '/repository-reviews_/profiles_/$profileID_/edit',
    path: '/repository-reviews/profiles/$profileID/edit',
    getParentRoute: () => rootRouteImport,
  } as any)
const RepositoryReviewsIdIssuesDraftIdRoute =
  RepositoryReviewsIdIssuesDraftIdRouteImport.update({
    id: '/repository-reviews_/$id_/issues_/$draftId',
    path: '/repository-reviews/$id/issues/$draftId',
    getParentRoute: () => rootRouteImport,
  } as any)
const RepositoryReviewsIdFindingsFindingIdRoute =
  RepositoryReviewsIdFindingsFindingIdRouteImport.update({
    id: '/repository-reviews_/$id_/findings_/$findingId',
    path: '/repository-reviews/$id/findings/$findingId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ModelsRoutersNameEditRoute = ModelsRoutersNameEditRouteImport.update({
  id: '/models_/routers_/$name_/edit',
  path: '/models/routers/$name/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const ModelsAliasesNameEditRoute = ModelsAliasesNameEditRouteImport.update({
  id: '/models_/aliases_/$name_/edit',
  path: '/models/aliases/$name/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentWorkflowsRunsIdRoute = AgentWorkflowsRunsIdRouteImport.update({
  id: '/workflows_/runs_/$id',
  path: '/workflows/runs/$id',
  getParentRoute: () => AgentRoute,
} as any)
const AgentWorkflowsIdEditRoute = AgentWorkflowsIdEditRouteImport.update({
  id: '/workflows_/$id_/edit',
  path: '/workflows/$id/edit',
  getParentRoute: () => AgentRoute,
} as any)
const AgentToolsSettingsAdaptationRoute =
  AgentToolsSettingsAdaptationRouteImport.update({
    id: '/tools_/settings_/adaptation',
    path: '/tools/settings/adaptation',
    getParentRoute: () => AgentRoute,
  } as any)
const AgentToolsIdEditRoute = AgentToolsIdEditRouteImport.update({
  id: '/tools_/$id_/edit',
  path: '/tools/$id/edit',
  getParentRoute: () => AgentRoute,
} as any)
const AgentMcpServersNewRoute = AgentMcpServersNewRouteImport.update({
  id: '/mcp_/servers_/new',
  path: '/mcp/servers/new',
  getParentRoute: () => AgentRoute,
} as any)
const AgentMcpServersNameRoute = AgentMcpServersNameRouteImport.update({
  id: '/mcp_/servers_/$name',
  path: '/mcp/servers/$name',
  getParentRoute: () => AgentRoute,
} as any)
const AgentAgentsIdEditRoute = AgentAgentsIdEditRouteImport.update({
  id: '/agents_/$id_/edit',
  path: '/agents/$id/edit',
  getParentRoute: () => AgentRoute,
} as any)
const AgentAgentsIdCapabilitiesRoute =
  AgentAgentsIdCapabilitiesRouteImport.update({
    id: '/agents_/$id_/capabilities',
    path: '/agents/$id/capabilities',
    getParentRoute: () => AgentRoute,
  } as any)
const AgentAgentsIdActivityRoute = AgentAgentsIdActivityRouteImport.update({
  id: '/agents_/$id_/activity',
  path: '/agents/$id/activity',
  getParentRoute: () => AgentRoute,
} as any)
const AccountsRoutersIdEditRoute = AccountsRoutersIdEditRouteImport.update({
  id: '/accounts_/routers_/$id_/edit',
  path: '/accounts/routers/$id/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const RepositoryReviewsRepositoriesIdFindingsFindingIdRoute =
  RepositoryReviewsRepositoriesIdFindingsFindingIdRouteImport.update({
    id: '/repository-reviews_/repositories_/$id_/findings_/$findingId',
    path: '/repository-reviews/repositories/$id/findings/$findingId',
    getParentRoute: () => rootRouteImport,
  } as any)
const RepositoryReviewsIdFindingsFindingIdLinkIssueRoute =
  RepositoryReviewsIdFindingsFindingIdLinkIssueRouteImport.update({
    id: '/repository-reviews_/$id_/findings_/$findingId_/link-issue',
    path: '/repository-reviews/$id/findings/$findingId/link-issue',
    getParentRoute: () => rootRouteImport,
  } as any)
const AgentMcpServersNameEditRoute = AgentMcpServersNameEditRouteImport.update({
  id: '/mcp_/servers_/$name_/edit',
  path: '/mcp/servers/$name/edit',
  getParentRoute: () => AgentRoute,
} as any)
const RepositoryReviewsRepositoriesIdFindingsFindingIdLinkIssueRoute =
  RepositoryReviewsRepositoriesIdFindingsFindingIdLinkIssueRouteImport.update({
    id: '/repository-reviews_/repositories_/$id_/findings_/$findingId_/link-issue',
    path: '/repository-reviews/repositories/$id/findings/$findingId/link-issue',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/channels': typeof ChannelsRouteRouteWithChildren
  '/accounts': typeof AccountsRoute
  '/agent': typeof AgentRouteWithChildren
  '/config': typeof ConfigRouteWithChildren
  '/development': typeof DevelopmentRoute
  '/event-sources': typeof EventSourcesRoute
  '/events': typeof EventsRoute
  '/launcher-login': typeof LauncherLoginRoute
  '/launcher-setup': typeof LauncherSetupRoute
  '/logs': typeof LogsRoute
  '/model-evaluations': typeof ModelEvaluationsRoute
  '/notifications': typeof NotificationsRoute
  '/repository-reviews': typeof RepositoryReviewsRoute
  '/threads': typeof ThreadsRouteWithChildren
  '/accounts/$id': typeof AccountsIdRoute
  '/accounts/new': typeof AccountsNewRoute
  '/accounts/routers': typeof AccountsRoutersRoute
  '/agent/agents': typeof AgentAgentsRoute
  '/agent/git-workspaces': typeof AgentGitWorkspacesRoute
  '/agent/hub': typeof AgentHubRoute
  '/agent/skills': typeof AgentSkillsRoute
  '/agent/tools': typeof AgentToolsRoute
  '/agent/workflows': typeof AgentWorkflowsRoute
  '/channels/$name': typeof ChannelsNameRoute
  '/config/raw': typeof ConfigRawRoute
  '/development/$workspaceID': typeof DevelopmentWorkspaceIDRoute
  '/development/new': typeof DevelopmentNewRoute
  '/development/repositories': typeof DevelopmentRepositoriesRoute
  '/development/settings': typeof DevelopmentSettingsRoute
  '/development/workflow-configurations': typeof DevelopmentWorkflowConfigurationsRoute
  '/event-sources/$id': typeof EventSourcesIdRoute
  '/event-sources/new': typeof EventSourcesNewRoute
  '/event-sources/settings': typeof EventSourcesSettingsRoute
  '/model-evaluations/$id': typeof ModelEvaluationsIdRoute
  '/model-evaluations/new': typeof ModelEvaluationsNewRoute
  '/models/aliases': typeof ModelsAliasesRoute
  '/models/routers': typeof ModelsRoutersRoute
  '/notifications/$notificationID': typeof NotificationsNotificationIDRoute
  '/repository-reviews/$id': typeof RepositoryReviewsIdRoute
  '/repository-reviews/profiles': typeof RepositoryReviewsProfilesRoute
  '/repository-reviews/repositories': typeof RepositoryReviewsRepositoriesRoute
  '/repository-reviews/results': typeof RepositoryReviewsResultsRoute
  '/threads/$threadId': typeof ThreadsThreadIdRoute
  '/threads/open': typeof ThreadsOpenRouteWithChildren
  '/threads/search': typeof ThreadsSearchRoute
  '/accounts/$id/edit': typeof AccountsIdEditRoute
  '/accounts/routers/$id': typeof AccountsRoutersIdRoute
  '/accounts/routers/new': typeof AccountsRoutersNewRoute
  '/agent/agents/$id': typeof AgentAgentsIdRoute
  '/agent/agents/new': typeof AgentAgentsNewRoute
  '/agent/git-workspaces/$id': typeof AgentGitWorkspacesIdRoute
  '/agent/git-workspaces/history': typeof AgentGitWorkspacesHistoryRoute
  '/agent/git-workspaces/settings': typeof AgentGitWorkspacesSettingsRoute
  '/agent/mcp/servers': typeof AgentMcpServersRoute
  '/agent/mcp/settings': typeof AgentMcpSettingsRoute
  '/agent/skills/$id': typeof AgentSkillsIdRoute
  '/agent/skills/new': typeof AgentSkillsNewRoute
  '/agent/tools/$id': typeof AgentToolsIdRoute
  '/agent/workflows/$id': typeof AgentWorkflowsIdRoute
  '/agent/workflows/new': typeof AgentWorkflowsNewRoute
  '/agent/workflows/runs': typeof AgentWorkflowsRunsRoute
  '/agent/workflows/settings': typeof AgentWorkflowsSettingsRoute
  '/event-sources/$id/edit': typeof EventSourcesIdEditRoute
  '/model-evaluations/$evaluationID/report': typeof ModelEvaluationsEvaluationIDReportRoute
  '/model-evaluations/$id/corpus': typeof ModelEvaluationsIdCorpusRoute
  '/model-evaluations/$id/edit': typeof ModelEvaluationsIdEditRoute
  '/model-evaluations/$id/languages': typeof ModelEvaluationsIdLanguagesRoute
  '/models/aliases/$name': typeof ModelsAliasesNameRoute
  '/models/aliases/new': typeof ModelsAliasesNewRoute
  '/models/routers/$name': typeof ModelsRoutersNameRoute
  '/models/routers/new': typeof ModelsRoutersNewRoute
  '/repository-reviews/$id/findings': typeof RepositoryReviewsIdFindingsRoute
  '/repository-reviews/$id/issues': typeof RepositoryReviewsIdIssuesRoute
  '/repository-reviews/$id/report': typeof RepositoryReviewsIdReportRoute
  '/repository-reviews/profiles/$profileID': typeof RepositoryReviewsProfilesProfileIDRoute
  '/repository-reviews/profiles/new': typeof RepositoryReviewsProfilesNewRoute
  '/repository-reviews/repositories/$id': typeof RepositoryReviewsRepositoriesIdRoute
  '/repository-reviews/repositories/new': typeof RepositoryReviewsRepositoriesNewRoute
  '/threads/open/$threadId': typeof ThreadsOpenThreadIdRoute
  '/accounts/routers/$id/edit': typeof AccountsRoutersIdEditRoute
  '/agent/agents/$id/activity': typeof AgentAgentsIdActivityRoute
  '/agent/agents/$id/capabilities': typeof AgentAgentsIdCapabilitiesRoute
  '/agent/agents/$id/edit': typeof AgentAgentsIdEditRoute
  '/agent/mcp/servers/$name': typeof AgentMcpServersNameRoute
  '/agent/mcp/servers/new': typeof AgentMcpServersNewRoute
  '/agent/tools/$id/edit': typeof AgentToolsIdEditRoute
  '/agent/tools/settings/adaptation': typeof AgentToolsSettingsAdaptationRoute
  '/agent/workflows/$id/edit': typeof AgentWorkflowsIdEditRoute
  '/agent/workflows/runs/$id': typeof AgentWorkflowsRunsIdRoute
  '/models/aliases/$name/edit': typeof ModelsAliasesNameEditRoute
  '/models/routers/$name/edit': typeof ModelsRoutersNameEditRoute
  '/repository-reviews/$id/findings/$findingId': typeof RepositoryReviewsIdFindingsFindingIdRoute
  '/repository-reviews/$id/issues/$draftId': typeof RepositoryReviewsIdIssuesDraftIdRoute
  '/repository-reviews/profiles/$profileID/edit': typeof RepositoryReviewsProfilesProfileIDEditRoute
  '/repository-reviews/repositories/$id/edit': typeof RepositoryReviewsRepositoriesIdEditRoute
  '/repository-reviews/repositories/$id/findings': typeof RepositoryReviewsRepositoriesIdFindingsRoute
  '/agent/mcp/servers/$name/edit': typeof AgentMcpServersNameEditRoute
  '/repository-reviews/$id/findings/$findingId/link-issue': typeof RepositoryReviewsIdFindingsFindingIdLinkIssueRoute
  '/repository-reviews/repositories/$id/findings/$findingId': typeof RepositoryReviewsRepositoriesIdFindingsFindingIdRoute
  '/repository-reviews/repositories/$id/findings/$findingId/link-issue': typeof RepositoryReviewsRepositoriesIdFindingsFindingIdLinkIssueRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/channels': typeof ChannelsRouteRouteWithChildren
  '/accounts': typeof AccountsRoute
  '/agent': typeof AgentRouteWithChildren
  '/config': typeof ConfigRouteWithChildren
  '/development': typeof DevelopmentRoute
  '/event-sources': typeof EventSourcesRoute
  '/events': typeof EventsRoute
  '/launcher-login': typeof LauncherLoginRoute
  '/launcher-setup': typeof LauncherSetupRoute
  '/logs': typeof LogsRoute
  '/model-evaluations': typeof ModelEvaluationsRoute
  '/notifications': typeof NotificationsRoute
  '/repository-reviews': typeof RepositoryReviewsRoute
  '/threads': typeof ThreadsRouteWithChildren
  '/accounts/$id': typeof AccountsIdRoute
  '/accounts/new': typeof AccountsNewRoute
  '/accounts/routers': typeof AccountsRoutersRoute
  '/agent/agents': typeof AgentAgentsRoute
  '/agent/git-workspaces': typeof AgentGitWorkspacesRoute
  '/agent/hub': typeof AgentHubRoute
  '/agent/skills': typeof AgentSkillsRoute
  '/agent/tools': typeof AgentToolsRoute
  '/agent/workflows': typeof AgentWorkflowsRoute
  '/channels/$name': typeof ChannelsNameRoute
  '/config/raw': typeof ConfigRawRoute
  '/development/$workspaceID': typeof DevelopmentWorkspaceIDRoute
  '/development/new': typeof DevelopmentNewRoute
  '/development/repositories': typeof DevelopmentRepositoriesRoute
  '/development/settings': typeof DevelopmentSettingsRoute
  '/development/workflow-configurations': typeof DevelopmentWorkflowConfigurationsRoute
  '/event-sources/$id': typeof EventSourcesIdRoute
  '/event-sources/new': typeof EventSourcesNewRoute
  '/event-sources/settings': typeof EventSourcesSettingsRoute
  '/model-evaluations/$id': typeof ModelEvaluationsIdRoute
  '/model-evaluations/new': typeof ModelEvaluationsNewRoute
  '/models/aliases': typeof ModelsAliasesRoute
  '/models/routers': typeof ModelsRoutersRoute
  '/notifications/$notificationID': typeof NotificationsNotificationIDRoute
  '/repository-reviews/$id': typeof RepositoryReviewsIdRoute
  '/repository-reviews/profiles': typeof RepositoryReviewsProfilesRoute
  '/repository-reviews/repositories': typeof RepositoryReviewsRepositoriesRoute
  '/repository-reviews/results': typeof RepositoryReviewsResultsRoute
  '/threads/$threadId': typeof ThreadsThreadIdRoute
  '/threads/open': typeof ThreadsOpenRouteWithChildren
  '/threads/search': typeof ThreadsSearchRoute
  '/accounts/$id/edit': typeof AccountsIdEditRoute
  '/accounts/routers/$id': typeof AccountsRoutersIdRoute
  '/accounts/routers/new': typeof AccountsRoutersNewRoute
  '/agent/agents/$id': typeof AgentAgentsIdRoute
  '/agent/agents/new': typeof AgentAgentsNewRoute
  '/agent/git-workspaces/$id': typeof AgentGitWorkspacesIdRoute
  '/agent/git-workspaces/history': typeof AgentGitWorkspacesHistoryRoute
  '/agent/git-workspaces/settings': typeof AgentGitWorkspacesSettingsRoute
  '/agent/mcp/servers': typeof AgentMcpServersRoute
  '/agent/mcp/settings': typeof AgentMcpSettingsRoute
  '/agent/skills/$id': typeof AgentSkillsIdRoute
  '/agent/skills/new': typeof AgentSkillsNewRoute
  '/agent/tools/$id': typeof AgentToolsIdRoute
  '/agent/workflows/$id': typeof AgentWorkflowsIdRoute
  '/agent/workflows/new': typeof AgentWorkflowsNewRoute
  '/agent/workflows/runs': typeof AgentWorkflowsRunsRoute
  '/agent/workflows/settings': typeof AgentWorkflowsSettingsRoute
  '/event-sources/$id/edit': typeof EventSourcesIdEditRoute
  '/model-evaluations/$evaluationID/report': typeof ModelEvaluationsEvaluationIDReportRoute
  '/model-evaluations/$id/corpus': typeof ModelEvaluationsIdCorpusRoute
  '/model-evaluations/$id/edit': typeof ModelEvaluationsIdEditRoute
  '/model-evaluations/$id/languages': typeof ModelEvaluationsIdLanguagesRoute
  '/models/aliases/$name': typeof ModelsAliasesNameRoute
  '/models/aliases/new': typeof ModelsAliasesNewRoute
  '/models/routers/$name': typeof ModelsRoutersNameRoute
  '/models/routers/new': typeof ModelsRoutersNewRoute
  '/repository-reviews/$id/findings': typeof RepositoryReviewsIdFindingsRoute
  '/repository-reviews/$id/issues': typeof RepositoryReviewsIdIssuesRoute
  '/repository-reviews/$id/report': typeof RepositoryReviewsIdReportRoute
  '/repository-reviews/profiles/$profileID': typeof RepositoryReviewsProfilesProfileIDRoute
  '/repository-reviews/profiles/new': typeof RepositoryReviewsProfilesNewRoute
  '/repository-reviews/repositories/$id': typeof RepositoryReviewsRepositoriesIdRoute
  '/repository-reviews/repositories/new': typeof RepositoryReviewsRepositoriesNewRoute
  '/threads/open/$threadId': typeof ThreadsOpenThreadIdRoute
  '/accounts/routers/$id/edit': typeof AccountsRoutersIdEditRoute
  '/agent/agents/$id/activity': typeof AgentAgentsIdActivityRoute
  '/agent/agents/$id/capabilities': typeof AgentAgentsIdCapabilitiesRoute
  '/agent/agents/$id/edit': typeof AgentAgentsIdEditRoute
  '/agent/mcp/servers/$name': typeof AgentMcpServersNameRoute
  '/agent/mcp/servers/new': typeof AgentMcpServersNewRoute
  '/agent/tools/$id/edit': typeof AgentToolsIdEditRoute
  '/agent/tools/settings/adaptation': typeof AgentToolsSettingsAdaptationRoute
  '/agent/workflows/$id/edit': typeof AgentWorkflowsIdEditRoute
  '/agent/workflows/runs/$id': typeof AgentWorkflowsRunsIdRoute
  '/models/aliases/$name/edit': typeof ModelsAliasesNameEditRoute
  '/models/routers/$name/edit': typeof ModelsRoutersNameEditRoute
  '/repository-reviews/$id/findings/$findingId': typeof RepositoryReviewsIdFindingsFindingIdRoute
  '/repository-reviews/$id/issues/$draftId': typeof RepositoryReviewsIdIssuesDraftIdRoute
  '/repository-reviews/profiles/$profileID/edit': typeof RepositoryReviewsProfilesProfileIDEditRoute
  '/repository-reviews/repositories/$id/edit': typeof RepositoryReviewsRepositoriesIdEditRoute
  '/repository-reviews/repositories/$id/findings': typeof RepositoryReviewsRepositoriesIdFindingsRoute
  '/agent/mcp/servers/$name/edit': typeof AgentMcpServersNameEditRoute
  '/repository-reviews/$id/findings/$findingId/link-issue': typeof RepositoryReviewsIdFindingsFindingIdLinkIssueRoute
  '/repository-reviews/repositories/$id/findings/$findingId': typeof RepositoryReviewsRepositoriesIdFindingsFindingIdRoute
  '/repository-reviews/repositories/$id/findings/$findingId/link-issue': typeof RepositoryReviewsRepositoriesIdFindingsFindingIdLinkIssueRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/channels': typeof ChannelsRouteRouteWithChildren
  '/accounts': typeof AccountsRoute
  '/agent': typeof AgentRouteWithChildren
  '/config': typeof ConfigRouteWithChildren
  '/development': typeof DevelopmentRoute
  '/event-sources': typeof EventSourcesRoute
  '/events': typeof EventsRoute
  '/launcher-login': typeof LauncherLoginRoute
  '/launcher-setup': typeof LauncherSetupRoute
  '/logs': typeof LogsRoute
  '/model-evaluations': typeof ModelEvaluationsRoute
  '/notifications': typeof NotificationsRoute
  '/repository-reviews': typeof RepositoryReviewsRoute
  '/threads': typeof ThreadsRouteWithChildren
  '/accounts_/$id': typeof AccountsIdRoute
  '/accounts_/new': typeof AccountsNewRoute
  '/accounts_/routers': typeof AccountsRoutersRoute
  '/agent/agents': typeof AgentAgentsRoute
  '/agent/git-workspaces': typeof AgentGitWorkspacesRoute
  '/agent/hub': typeof AgentHubRoute
  '/agent/skills': typeof AgentSkillsRoute
  '/agent/tools': typeof AgentToolsRoute
  '/agent/workflows': typeof AgentWorkflowsRoute
  '/channels/$name': typeof ChannelsNameRoute
  '/config/raw': typeof ConfigRawRoute
  '/development_/$workspaceID': typeof DevelopmentWorkspaceIDRoute
  '/development_/new': typeof DevelopmentNewRoute
  '/development_/repositories': typeof DevelopmentRepositoriesRoute
  '/development_/settings': typeof DevelopmentSettingsRoute
  '/development_/workflow-configurations': typeof DevelopmentWorkflowConfigurationsRoute
  '/event-sources_/$id': typeof EventSourcesIdRoute
  '/event-sources_/new': typeof EventSourcesNewRoute
  '/event-sources_/settings': typeof EventSourcesSettingsRoute
  '/model-evaluations_/$id': typeof ModelEvaluationsIdRoute
  '/model-evaluations_/new': typeof ModelEvaluationsNewRoute
  '/models_/aliases': typeof ModelsAliasesRoute
  '/models_/routers': typeof ModelsRoutersRoute
  '/notifications_/$notificationID': typeof NotificationsNotificationIDRoute
  '/repository-reviews_/$id': typeof RepositoryReviewsIdRoute
  '/repository-reviews_/profiles': typeof RepositoryReviewsProfilesRoute
  '/repository-reviews_/repositories': typeof RepositoryReviewsRepositoriesRoute
  '/repository-reviews_/results': typeof RepositoryReviewsResultsRoute
  '/threads/$threadId': typeof ThreadsThreadIdRoute
  '/threads/open': typeof ThreadsOpenRouteWithChildren
  '/threads/search': typeof ThreadsSearchRoute
  '/accounts_/$id_/edit': typeof AccountsIdEditRoute
  '/accounts_/routers_/$id': typeof AccountsRoutersIdRoute
  '/accounts_/routers_/new': typeof AccountsRoutersNewRoute
  '/agent/agents_/$id': typeof AgentAgentsIdRoute
  '/agent/agents_/new': typeof AgentAgentsNewRoute
  '/agent/git-workspaces_/$id': typeof AgentGitWorkspacesIdRoute
  '/agent/git-workspaces_/history': typeof AgentGitWorkspacesHistoryRoute
  '/agent/git-workspaces_/settings': typeof AgentGitWorkspacesSettingsRoute
  '/agent/mcp_/servers': typeof AgentMcpServersRoute
  '/agent/mcp_/settings': typeof AgentMcpSettingsRoute
  '/agent/skills_/$id': typeof AgentSkillsIdRoute
  '/agent/skills_/new': typeof AgentSkillsNewRoute
  '/agent/tools_/$id': typeof AgentToolsIdRoute
  '/agent/workflows_/$id': typeof AgentWorkflowsIdRoute
  '/agent/workflows_/new': typeof AgentWorkflowsNewRoute
  '/agent/workflows_/runs': typeof AgentWorkflowsRunsRoute
  '/agent/workflows_/settings': typeof AgentWorkflowsSettingsRoute
  '/event-sources_/$id_/edit': typeof EventSourcesIdEditRoute
  '/model-evaluations_/$evaluationID/report': typeof ModelEvaluationsEvaluationIDReportRoute
  '/model-evaluations_/$id_/corpus': typeof ModelEvaluationsIdCorpusRoute
  '/model-evaluations_/$id_/edit': typeof ModelEvaluationsIdEditRoute
  '/model-evaluations_/$id_/languages': typeof ModelEvaluationsIdLanguagesRoute
  '/models_/aliases_/$name': typeof ModelsAliasesNameRoute
  '/models_/aliases_/new': typeof ModelsAliasesNewRoute
  '/models_/routers_/$name': typeof ModelsRoutersNameRoute
  '/models_/routers_/new': typeof ModelsRoutersNewRoute
  '/repository-reviews_/$id_/findings': typeof RepositoryReviewsIdFindingsRoute
  '/repository-reviews_/$id_/issues': typeof RepositoryReviewsIdIssuesRoute
  '/repository-reviews_/$id_/report': typeof RepositoryReviewsIdReportRoute
  '/repository-reviews_/profiles_/$profileID': typeof RepositoryReviewsProfilesProfileIDRoute
  '/repository-reviews_/profiles_/new': typeof RepositoryReviewsProfilesNewRoute
  '/repository-reviews_/repositories_/$id': typeof RepositoryReviewsRepositoriesIdRoute
  '/repository-reviews_/repositories_/new': typeof RepositoryReviewsRepositoriesNewRoute
  '/threads/open/$threadId': typeof ThreadsOpenThreadIdRoute
  '/accounts_/routers_/$id_/edit': typeof AccountsRoutersIdEditRoute
  '/agent/agents_/$id_/activity': typeof AgentAgentsIdActivityRoute
  '/agent/agents_/$id_/capabilities': typeof AgentAgentsIdCapabilitiesRoute
  '/agent/agents_/$id_/edit': typeof AgentAgentsIdEditRoute
  '/agent/mcp_/servers_/$name': typeof AgentMcpServersNameRoute
  '/agent/mcp_/servers_/new': typeof AgentMcpServersNewRoute
  '/agent/tools_/$id_/edit': typeof AgentToolsIdEditRoute
  '/agent/tools_/settings_/adaptation': typeof AgentToolsSettingsAdaptationRoute
  '/agent/workflows_/$id_/edit': typeof AgentWorkflowsIdEditRoute
  '/agent/workflows_/runs_/$id': typeof AgentWorkflowsRunsIdRoute
  '/models_/aliases_/$name_/edit': typeof ModelsAliasesNameEditRoute
  '/models_/routers_/$name_/edit': typeof ModelsRoutersNameEditRoute
  '/repository-reviews_/$id_/findings_/$findingId': typeof RepositoryReviewsIdFindingsFindingIdRoute
  '/repository-reviews_/$id_/issues_/$draftId': typeof RepositoryReviewsIdIssuesDraftIdRoute
  '/repository-reviews_/profiles_/$profileID_/edit': typeof RepositoryReviewsProfilesProfileIDEditRoute
  '/repository-reviews_/repositories_/$id_/edit': typeof RepositoryReviewsRepositoriesIdEditRoute
  '/repository-reviews_/repositories_/$id_/findings': typeof RepositoryReviewsRepositoriesIdFindingsRoute
  '/agent/mcp_/servers_/$name_/edit': typeof AgentMcpServersNameEditRoute
  '/repository-reviews_/$id_/findings_/$findingId_/link-issue': typeof RepositoryReviewsIdFindingsFindingIdLinkIssueRoute
  '/repository-reviews_/repositories_/$id_/findings_/$findingId': typeof RepositoryReviewsRepositoriesIdFindingsFindingIdRoute
  '/repository-reviews_/repositories_/$id_/findings_/$findingId_/link-issue': typeof RepositoryReviewsRepositoriesIdFindingsFindingIdLinkIssueRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/channels'
    | '/accounts'
    | '/agent'
    | '/config'
    | '/development'
    | '/event-sources'
    | '/events'
    | '/launcher-login'
    | '/launcher-setup'
    | '/logs'
    | '/model-evaluations'
    | '/notifications'
    | '/repository-reviews'
    | '/threads'
    | '/accounts/$id'
    | '/accounts/new'
    | '/accounts/routers'
    | '/agent/agents'
    | '/agent/git-workspaces'
    | '/agent/hub'
    | '/agent/skills'
    | '/agent/tools'
    | '/agent/workflows'
    | '/channels/$name'
    | '/config/raw'
    | '/development/$workspaceID'
    | '/development/new'
    | '/development/repositories'
    | '/development/settings'
    | '/development/workflow-configurations'
    | '/event-sources/$id'
    | '/event-sources/new'
    | '/event-sources/settings'
    | '/model-evaluations/$id'
    | '/model-evaluations/new'
    | '/models/aliases'
    | '/models/routers'
    | '/notifications/$notificationID'
    | '/repository-reviews/$id'
    | '/repository-reviews/profiles'
    | '/repository-reviews/repositories'
    | '/repository-reviews/results'
    | '/threads/$threadId'
    | '/threads/open'
    | '/threads/search'
    | '/accounts/$id/edit'
    | '/accounts/routers/$id'
    | '/accounts/routers/new'
    | '/agent/agents/$id'
    | '/agent/agents/new'
    | '/agent/git-workspaces/$id'
    | '/agent/git-workspaces/history'
    | '/agent/git-workspaces/settings'
    | '/agent/mcp/servers'
    | '/agent/mcp/settings'
    | '/agent/skills/$id'
    | '/agent/skills/new'
    | '/agent/tools/$id'
    | '/agent/workflows/$id'
    | '/agent/workflows/new'
    | '/agent/workflows/runs'
    | '/agent/workflows/settings'
    | '/event-sources/$id/edit'
    | '/model-evaluations/$evaluationID/report'
    | '/model-evaluations/$id/corpus'
    | '/model-evaluations/$id/edit'
    | '/model-evaluations/$id/languages'
    | '/models/aliases/$name'
    | '/models/aliases/new'
    | '/models/routers/$name'
    | '/models/routers/new'
    | '/repository-reviews/$id/findings'
    | '/repository-reviews/$id/issues'
    | '/repository-reviews/$id/report'
    | '/repository-reviews/profiles/$profileID'
    | '/repository-reviews/profiles/new'
    | '/repository-reviews/repositories/$id'
    | '/repository-reviews/repositories/new'
    | '/threads/open/$threadId'
    | '/accounts/routers/$id/edit'
    | '/agent/agents/$id/activity'
    | '/agent/agents/$id/capabilities'
    | '/agent/agents/$id/edit'
    | '/agent/mcp/servers/$name'
    | '/agent/mcp/servers/new'
    | '/agent/tools/$id/edit'
    | '/agent/tools/settings/adaptation'
    | '/agent/workflows/$id/edit'
    | '/agent/workflows/runs/$id'
    | '/models/aliases/$name/edit'
    | '/models/routers/$name/edit'
    | '/repository-reviews/$id/findings/$findingId'
    | '/repository-reviews/$id/issues/$draftId'
    | '/repository-reviews/profiles/$profileID/edit'
    | '/repository-reviews/repositories/$id/edit'
    | '/repository-reviews/repositories/$id/findings'
    | '/agent/mcp/servers/$name/edit'
    | '/repository-reviews/$id/findings/$findingId/link-issue'
    | '/repository-reviews/repositories/$id/findings/$findingId'
    | '/repository-reviews/repositories/$id/findings/$findingId/link-issue'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/channels'
    | '/accounts'
    | '/agent'
    | '/config'
    | '/development'
    | '/event-sources'
    | '/events'
    | '/launcher-login'
    | '/launcher-setup'
    | '/logs'
    | '/model-evaluations'
    | '/notifications'
    | '/repository-reviews'
    | '/threads'
    | '/accounts/$id'
    | '/accounts/new'
    | '/accounts/routers'
    | '/agent/agents'
    | '/agent/git-workspaces'
    | '/agent/hub'
    | '/agent/skills'
    | '/agent/tools'
    | '/agent/workflows'
    | '/channels/$name'
    | '/config/raw'
    | '/development/$workspaceID'
    | '/development/new'
    | '/development/repositories'
    | '/development/settings'
    | '/development/workflow-configurations'
    | '/event-sources/$id'
    | '/event-sources/new'
    | '/event-sources/settings'
    | '/model-evaluations/$id'
    | '/model-evaluations/new'
    | '/models/aliases'
    | '/models/routers'
    | '/notifications/$notificationID'
    | '/repository-reviews/$id'
    | '/repository-reviews/profiles'
    | '/repository-reviews/repositories'
    | '/repository-reviews/results'
    | '/threads/$threadId'
    | '/threads/open'
    | '/threads/search'
    | '/accounts/$id/edit'
    | '/accounts/routers/$id'
    | '/accounts/routers/new'
    | '/agent/agents/$id'
    | '/agent/agents/new'
    | '/agent/git-workspaces/$id'
    | '/agent/git-workspaces/history'
    | '/agent/git-workspaces/settings'
    | '/agent/mcp/servers'
    | '/agent/mcp/settings'
    | '/agent/skills/$id'
    | '/agent/skills/new'
    | '/agent/tools/$id'
    | '/agent/workflows/$id'
    | '/agent/workflows/new'
    | '/agent/workflows/runs'
    | '/agent/workflows/settings'
    | '/event-sources/$id/edit'
    | '/model-evaluations/$evaluationID/report'
    | '/model-evaluations/$id/corpus'
    | '/model-evaluations/$id/edit'
    | '/model-evaluations/$id/languages'
    | '/models/aliases/$name'
    | '/models/aliases/new'
    | '/models/routers/$name'
    | '/models/routers/new'
    | '/repository-reviews/$id/findings'
    | '/repository-reviews/$id/issues'
    | '/repository-reviews/$id/report'
    | '/repository-reviews/profiles/$profileID'
    | '/repository-reviews/profiles/new'
    | '/repository-reviews/repositories/$id'
    | '/repository-reviews/repositories/new'
    | '/threads/open/$threadId'
    | '/accounts/routers/$id/edit'
    | '/agent/agents/$id/activity'
    | '/agent/agents/$id/capabilities'
    | '/agent/agents/$id/edit'
    | '/agent/mcp/servers/$name'
    | '/agent/mcp/servers/new'
    | '/agent/tools/$id/edit'
    | '/agent/tools/settings/adaptation'
    | '/agent/workflows/$id/edit'
    | '/agent/workflows/runs/$id'
    | '/models/aliases/$name/edit'
    | '/models/routers/$name/edit'
    | '/repository-reviews/$id/findings/$findingId'
    | '/repository-reviews/$id/issues/$draftId'
    | '/repository-reviews/profiles/$profileID/edit'
    | '/repository-reviews/repositories/$id/edit'
    | '/repository-reviews/repositories/$id/findings'
    | '/agent/mcp/servers/$name/edit'
    | '/repository-reviews/$id/findings/$findingId/link-issue'
    | '/repository-reviews/repositories/$id/findings/$findingId'
    | '/repository-reviews/repositories/$id/findings/$findingId/link-issue'
  id:
    | '__root__'
    | '/'
    | '/channels'
    | '/accounts'
    | '/agent'
    | '/config'
    | '/development'
    | '/event-sources'
    | '/events'
    | '/launcher-login'
    | '/launcher-setup'
    | '/logs'
    | '/model-evaluations'
    | '/notifications'
    | '/repository-reviews'
    | '/threads'
    | '/accounts_/$id'
    | '/accounts_/new'
    | '/accounts_/routers'
    | '/agent/agents'
    | '/agent/git-workspaces'
    | '/agent/hub'
    | '/agent/skills'
    | '/agent/tools'
    | '/agent/workflows'
    | '/channels/$name'
    | '/config/raw'
    | '/development_/$workspaceID'
    | '/development_/new'
    | '/development_/repositories'
    | '/development_/settings'
    | '/development_/workflow-configurations'
    | '/event-sources_/$id'
    | '/event-sources_/new'
    | '/event-sources_/settings'
    | '/model-evaluations_/$id'
    | '/model-evaluations_/new'
    | '/models_/aliases'
    | '/models_/routers'
    | '/notifications_/$notificationID'
    | '/repository-reviews_/$id'
    | '/repository-reviews_/profiles'
    | '/repository-reviews_/repositories'
    | '/repository-reviews_/results'
    | '/threads/$threadId'
    | '/threads/open'
    | '/threads/search'
    | '/accounts_/$id_/edit'
    | '/accounts_/routers_/$id'
    | '/accounts_/routers_/new'
    | '/agent/agents_/$id'
    | '/agent/agents_/new'
    | '/agent/git-workspaces_/$id'
    | '/agent/git-workspaces_/history'
    | '/agent/git-workspaces_/settings'
    | '/agent/mcp_/servers'
    | '/agent/mcp_/settings'
    | '/agent/skills_/$id'
    | '/agent/skills_/new'
    | '/agent/tools_/$id'
    | '/agent/workflows_/$id'
    | '/agent/workflows_/new'
    | '/agent/workflows_/runs'
    | '/agent/workflows_/settings'
    | '/event-sources_/$id_/edit'
    | '/model-evaluations_/$evaluationID/report'
    | '/model-evaluations_/$id_/corpus'
    | '/model-evaluations_/$id_/edit'
    | '/model-evaluations_/$id_/languages'
    | '/models_/aliases_/$name'
    | '/models_/aliases_/new'
    | '/models_/routers_/$name'
    | '/models_/routers_/new'
    | '/repository-reviews_/$id_/findings'
    | '/repository-reviews_/$id_/issues'
    | '/repository-reviews_/$id_/report'
    | '/repository-reviews_/profiles_/$profileID'
    | '/repository-reviews_/profiles_/new'
    | '/repository-reviews_/repositories_/$id'
    | '/repository-reviews_/repositories_/new'
    | '/threads/open/$threadId'
    | '/accounts_/routers_/$id_/edit'
    | '/agent/agents_/$id_/activity'
    | '/agent/agents_/$id_/capabilities'
    | '/agent/agents_/$id_/edit'
    | '/agent/mcp_/servers_/$name'
    | '/agent/mcp_/servers_/new'
    | '/agent/tools_/$id_/edit'
    | '/agent/tools_/settings_/adaptation'
    | '/agent/workflows_/$id_/edit'
    | '/agent/workflows_/runs_/$id'
    | '/models_/aliases_/$name_/edit'
    | '/models_/routers_/$name_/edit'
    | '/repository-reviews_/$id_/findings_/$findingId'
    | '/repository-reviews_/$id_/issues_/$draftId'
    | '/repository-reviews_/profiles_/$profileID_/edit'
    | '/repository-reviews_/repositories_/$id_/edit'
    | '/repository-reviews_/repositories_/$id_/findings'
    | '/agent/mcp_/servers_/$name_/edit'
    | '/repository-reviews_/$id_/findings_/$findingId_/link-issue'
    | '/repository-reviews_/repositories_/$id_/findings_/$findingId'
    | '/repository-reviews_/repositories_/$id_/findings_/$findingId_/link-issue'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChannelsRouteRoute: typeof ChannelsRouteRouteWithChildren
  AccountsRoute: typeof AccountsRoute
  AgentRoute: typeof AgentRouteWithChildren
  ConfigRoute: typeof ConfigRouteWithChildren
  DevelopmentRoute: typeof DevelopmentRoute
  EventSourcesRoute: typeof EventSourcesRoute
  EventsRoute: typeof EventsRoute
  LauncherLoginRoute: typeof LauncherLoginRoute
  LauncherSetupRoute: typeof LauncherSetupRoute
  LogsRoute: typeof LogsRoute
  ModelEvaluationsRoute: typeof ModelEvaluationsRoute
  NotificationsRoute: typeof NotificationsRoute
  RepositoryReviewsRoute: typeof RepositoryReviewsRoute
  ThreadsRoute: typeof ThreadsRouteWithChildren
  AccountsIdRoute: typeof AccountsIdRoute
  AccountsNewRoute: typeof AccountsNewRoute
  AccountsRoutersRoute: typeof AccountsRoutersRoute
  DevelopmentWorkspaceIDRoute: typeof DevelopmentWorkspaceIDRoute
  DevelopmentNewRoute: typeof DevelopmentNewRoute
  DevelopmentRepositoriesRoute: typeof DevelopmentRepositoriesRoute
  DevelopmentSettingsRoute: typeof DevelopmentSettingsRoute
  DevelopmentWorkflowConfigurationsRoute: typeof DevelopmentWorkflowConfigurationsRoute
  EventSourcesIdRoute: typeof EventSourcesIdRoute
  EventSourcesNewRoute: typeof EventSourcesNewRoute
  EventSourcesSettingsRoute: typeof EventSourcesSettingsRoute
  ModelEvaluationsIdRoute: typeof ModelEvaluationsIdRoute
  ModelEvaluationsNewRoute: typeof ModelEvaluationsNewRoute
  ModelsAliasesRoute: typeof ModelsAliasesRoute
  ModelsRoutersRoute: typeof ModelsRoutersRoute
  NotificationsNotificationIDRoute: typeof NotificationsNotificationIDRoute
  RepositoryReviewsIdRoute: typeof RepositoryReviewsIdRoute
  RepositoryReviewsProfilesRoute: typeof RepositoryReviewsProfilesRoute
  RepositoryReviewsRepositoriesRoute: typeof RepositoryReviewsRepositoriesRoute
  RepositoryReviewsResultsRoute: typeof RepositoryReviewsResultsRoute
  AccountsIdEditRoute: typeof AccountsIdEditRoute
  AccountsRoutersIdRoute: typeof AccountsRoutersIdRoute
  AccountsRoutersNewRoute: typeof AccountsRoutersNewRoute
  EventSourcesIdEditRoute: typeof EventSourcesIdEditRoute
  ModelEvaluationsEvaluationIDReportRoute: typeof ModelEvaluationsEvaluationIDReportRoute
  ModelEvaluationsIdCorpusRoute: typeof ModelEvaluationsIdCorpusRoute
  ModelEvaluationsIdEditRoute: typeof ModelEvaluationsIdEditRoute
  ModelEvaluationsIdLanguagesRoute: typeof ModelEvaluationsIdLanguagesRoute
  ModelsAliasesNameRoute: typeof ModelsAliasesNameRoute
  ModelsAliasesNewRoute: typeof ModelsAliasesNewRoute
  ModelsRoutersNameRoute: typeof ModelsRoutersNameRoute
  ModelsRoutersNewRoute: typeof ModelsRoutersNewRoute
  RepositoryReviewsIdFindingsRoute: typeof RepositoryReviewsIdFindingsRoute
  RepositoryReviewsIdIssuesRoute: typeof RepositoryReviewsIdIssuesRoute
  RepositoryReviewsIdReportRoute: typeof RepositoryReviewsIdReportRoute
  RepositoryReviewsProfilesProfileIDRoute: typeof RepositoryReviewsProfilesProfileIDRoute
  RepositoryReviewsProfilesNewRoute: typeof RepositoryReviewsProfilesNewRoute
  RepositoryReviewsRepositoriesIdRoute: typeof RepositoryReviewsRepositoriesIdRoute
  RepositoryReviewsRepositoriesNewRoute: typeof RepositoryReviewsRepositoriesNewRoute
  AccountsRoutersIdEditRoute: typeof AccountsRoutersIdEditRoute
  ModelsAliasesNameEditRoute: typeof ModelsAliasesNameEditRoute
  ModelsRoutersNameEditRoute: typeof ModelsRoutersNameEditRoute
  RepositoryReviewsIdFindingsFindingIdRoute: typeof RepositoryReviewsIdFindingsFindingIdRoute
  RepositoryReviewsIdIssuesDraftIdRoute: typeof RepositoryReviewsIdIssuesDraftIdRoute
  RepositoryReviewsProfilesProfileIDEditRoute: typeof RepositoryReviewsProfilesProfileIDEditRoute
  RepositoryReviewsRepositoriesIdEditRoute: typeof RepositoryReviewsRepositoriesIdEditRoute
  RepositoryReviewsRepositoriesIdFindingsRoute: typeof RepositoryReviewsRepositoriesIdFindingsRoute
  RepositoryReviewsIdFindingsFindingIdLinkIssueRoute: typeof RepositoryReviewsIdFindingsFindingIdLinkIssueRoute
  RepositoryReviewsRepositoriesIdFindingsFindingIdRoute: typeof RepositoryReviewsRepositoriesIdFindingsFindingIdRoute
  RepositoryReviewsRepositoriesIdFindingsFindingIdLinkIssueRoute: typeof RepositoryReviewsRepositoriesIdFindingsFindingIdLinkIssueRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/threads': {
      id: '/threads'
      path: '/threads'
      fullPath: '/threads'
      preLoaderRoute: typeof ThreadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/repository-reviews': {
      id: '/repository-reviews'
      path: '/repository-reviews'
      fullPath: '/repository-reviews'
      preLoaderRoute: typeof RepositoryReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/model-evaluations': {
      id: '/model-evaluations'
      path: '/model-evaluations'
      fullPath: '/model-evaluations'
      preLoaderRoute: typeof ModelEvaluationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logs': {
      id: '/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof LogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/launcher-setup': {
      id: '/launcher-setup'
      path: '/launcher-setup'
      fullPath: '/launcher-setup'
      preLoaderRoute: typeof LauncherSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/launcher-login': {
      id: '/launcher-login'
      path: '/launcher-login'
      fullPath: '/launcher-login'
      preLoaderRoute: typeof LauncherLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/event-sources': {
      id: '/event-sources'
      path: '/event-sources'
      fullPath: '/event-sources'
      preLoaderRoute: typeof EventSourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/development': {
      id: '/development'
      path: '/development'
      fullPath: '/development'
      preLoaderRoute: typeof DevelopmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/config': {
      id: '/config'
      path: '/config'
      fullPath: '/config'
      preLoaderRoute: typeof ConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent': {
      id: '/agent'
      path: '/agent'
      fullPath: '/agent'
      preLoaderRoute: typeof AgentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounts': {
      id: '/accounts'
      path: '/accounts'
      fullPath: '/accounts'
      preLoaderRoute: typeof AccountsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/channels': {
      id: '/channels'
      path: '/channels'
      fullPath: '/channels'
      preLoaderRoute: typeof ChannelsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/threads/search': {
      id: '/threads/search'
      path: '/search'
      fullPath: '/threads/search'
      preLoaderRoute: typeof ThreadsSearchRouteImport
      parentRoute: typeof ThreadsRoute
    }
    '/threads/open': {
      id: '/threads/open'
      path: '/open'
      fullPath: '/threads/open'
      preLoaderRoute: typeof ThreadsOpenRouteImport
      parentRoute: typeof ThreadsRoute
    }
    '/threads/$threadId': {
      id: '/threads/$threadId'
      path: '/$threadId'
      fullPath: '/threads/$threadId'
      preLoaderRoute: typeof ThreadsThreadIdRouteImport
      parentRoute: typeof ThreadsRoute
    }
    '/repository-reviews_/results': {
      id: '/repository-reviews_/results'
      path: '/repository-reviews/results'
      fullPath: '/repository-reviews/results'
      preLoaderRoute: typeof RepositoryReviewsResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/repository-reviews_/repositories': {
      id: '/repository-reviews_/repositories'
      path: '/repository-reviews/repositories'
      fullPath: '/repository-reviews/repositories'
      preLoaderRoute: typeof RepositoryReviewsRepositoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/repository-reviews_/profiles': {
      id: '/repository-reviews_/profiles'
      path: '/repository-reviews/profiles'
      fullPath: '/repository-reviews/profiles'
      preLoaderRoute: typeof RepositoryReviewsProfilesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/repository-reviews_/$id': {
      id: '/repository-reviews_/$id'
      path: '/repository-reviews/$id'
      fullPath: '/repository-reviews/$id'
      preLoaderRoute: typeof RepositoryReviewsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications_/$notificationID': {
      id: '/notifications_/$notificationID'
      path: '/notifications/$notificationID'
      fullPath: '/notifications/$notificationID'
      preLoaderRoute: typeof NotificationsNotificationIDRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/models_/routers': {
      id: '/models_/routers'
      path: '/models/routers'
      fullPath: '/models/routers'
      preLoaderRoute: typeof ModelsRoutersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/models_/aliases': {
      id: '/models_/aliases'
      path: '/models/aliases'
      fullPath: '/models/aliases'
      preLoaderRoute: typeof ModelsAliasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/model-evaluations_/new': {
      id: '/model-evaluations_/new'
      path: '/model-evaluations/new'
      fullPath: '/model-evaluations/new'
      preLoaderRoute: typeof ModelEvaluationsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/model-evaluations_/$id': {
      id: '/model-evaluations_/$id'
      path: '/model-evaluations/$id'
      fullPath: '/model-evaluations/$id'
      preLoaderRoute: typeof ModelEvaluationsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/event-sources_/settings': {
      id: '/event-sources_/settings'
      path: '/event-sources/settings'
      fullPath: '/event-sources/settings'
      preLoaderRoute: typeof EventSourcesSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/event-sources_/new': {
      id: '/event-sources_/new'
      path: '/event-sources/new'
      fullPath: '/event-sources/new'
      preLoaderRoute: typeof EventSourcesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/event-sources_/$id': {
      id: '/event-sources_/$id'
      path: '/event-sources/$id'
      fullPath: '/event-sources/$id'
      preLoaderRoute: typeof EventSourcesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/development_/workflow-configurations': {
      id: '/development_/workflow-configurations'
      path: '/development/workflow-configurations'
      fullPath: '/development/workflow-configurations'
      preLoaderRoute: typeof DevelopmentWorkflowConfigurationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/development_/settings': {
      id: '/development_/settings'
      path: '/development/settings'
      fullPath: '/development/settings'
      preLoaderRoute: typeof DevelopmentSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/development_/repositories': {
      id: '/development_/repositories'
      path: '/development/repositories'
      fullPath: '/development/repositories'
      preLoaderRoute: typeof DevelopmentRepositoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/development_/new': {
      id: '/development_/new'
      path: '/development/new'
      fullPath: '/development/new'
      preLoaderRoute: typeof DevelopmentNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/development_/$workspaceID': {
      id: '/development_/$workspaceID'
      path: '/development/$workspaceID'
      fullPath: '/development/$workspaceID'
      preLoaderRoute: typeof DevelopmentWorkspaceIDRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/config/raw': {
      id: '/config/raw'
      path: '/raw'
      fullPath: '/config/raw'
      preLoaderRoute: typeof ConfigRawRouteImport
      parentRoute: typeof ConfigRoute
    }
    '/channels/$name': {
      id: '/channels/$name'
      path: '/$name'
      fullPath: '/channels/$name'
      preLoaderRoute: typeof ChannelsNameRouteImport
      parentRoute: typeof ChannelsRouteRoute
    }
    '/agent/workflows': {
      id: '/agent/workflows'
      path: '/workflows'
      fullPath: '/agent/workflows'
      preLoaderRoute: typeof AgentWorkflowsRouteImport
      parentRoute: typeof AgentRoute
    }
    '/agent/tools': {
      id: '/agent/tools'
      path: '/tools'
      fullPath: '/agent/tools'
      preLoaderRoute: typeof AgentToolsRouteImport
      parentRoute: typeof AgentRoute
    }
    '/agent/skills': {
      id: '/agent/skills'
      path: '/skills'
      fullPath: '/agent/skills'
      preLoaderRoute: typeof AgentSkillsRouteImport
      parentRoute: typeof AgentRoute
    }
    '/agent/hub': {
      id: '/agent/hub'
      path: '/hub'
      fullPath: '/agent/hub'
      preLoaderRoute: typeof AgentHubRouteImport
      parentRoute: typeof AgentRoute
    }
    '/agent/git-workspaces': {
      id: '/agent/git-workspaces'
      path: '/git-workspaces'
      fullPath: '/agent/git-workspaces'
      preLoaderRoute: typeof AgentGitWorkspacesRouteImport
      parentRoute: typeof AgentRoute
    }
    '/agent/agents': {
      id: '/agent/agents'
      path: '/agents'
      fullPath: '/agent/agents'
      preLoaderRoute: typeof AgentAgentsRouteImport
      parentRoute: typeof AgentRoute
    }
    '/accounts_/routers': {
      id: '/accounts_/routers'
      path: '/accounts/routers'
      fullPath: '/accounts/routers'
      preLoaderRoute: typeof AccountsRoutersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounts_/new': {
      id: '/accounts_/new'
      path: '/accounts/new'
      fullPath: '/accounts/new'
      preLoaderRoute: typeof AccountsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounts_/$id': {
      id: '/accounts_/$id'
      path: '/accounts/$id'
      fullPath: '/accounts/$id'
      preLoaderRoute: typeof AccountsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/threads/open/$threadId': {
      id: '/threads/open/$threadId'
      path: '/$threadId'
      fullPath: '/threads/open/$threadId'
      preLoaderRoute: typeof ThreadsOpenThreadIdRouteImport
      parentRoute: typeof ThreadsOpenRoute
    }
    '/repository-reviews_/repositories_/new': {
      id: '/repository-reviews_/repositories_/new'
      path: '/repository-reviews/repositories/new'
      fullPath: '/repository-reviews/repositories/new'
      preLoaderRoute: typeof RepositoryReviewsRepositoriesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/repository-reviews_/repositories_/$id': {
      id: '/repository-reviews_/repositories_/$id'
      path: '/repository-reviews/repositories/$id'
      fullPath: '/repository-reviews/repositories/$id'
      preLoaderRoute: typeof RepositoryReviewsRepositoriesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/repository-reviews_/profiles_/new': {
      id: '/repository-reviews_/profiles_/new'
      path: '/repository-reviews/profiles/new'
      fullPath: '/repository-reviews/profiles/new'
      preLoaderRoute: typeof RepositoryReviewsProfilesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/repository-reviews_/profiles_/$profileID': {
      id: '/repository-reviews_/profiles_/$profileID'
      path: '/repository-reviews/profiles/$profileID'
      fullPath: '/repository-reviews/profiles/$profileID'
      preLoaderRoute: typeof RepositoryReviewsProfilesProfileIDRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/repository-reviews_/$id_/report': {
      id: '/repository-reviews_/$id_/report'
      path: '/repository-reviews/$id/report'
      fullPath: '/repository-reviews/$id/report'
      preLoaderRoute: typeof RepositoryReviewsIdReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/repository-reviews_/$id_/issues': {
      id: '/repository-reviews_/$id_/issues'
      path: '/repository-reviews/$id/issues'
      fullPath: '/repository-reviews/$id/issues'
      preLoaderRoute: typeof RepositoryReviewsIdIssuesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/repository-reviews_/$id_/findings': {
      id: '/repository-reviews_/$id_/findings'
      path: '/repository-reviews/$id/findings'
      fullPath: '/repository-reviews/$id/findings'
      preLoaderRoute: typeof RepositoryReviewsIdFindingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/models_/routers_/new': {
      id: '/models_/routers_/new'
      path: '/models/routers/new'
      fullPath: '/models/routers/new'
      preLoaderRoute: typeof ModelsRoutersNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/models_/routers_/$name': {
      id: '/models_/routers_/$name'
      path: '/models/routers/$name'
      fullPath: '/models/routers/$name'
      preLoaderRoute: typeof ModelsRoutersNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/models_/aliases_/new': {
      id: '/models_/aliases_/new'
      path: '/models/aliases/new'
      fullPath: '/models/aliases/new'
      preLoaderRoute: typeof ModelsAliasesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/models_/aliases_/$name': {
      id: '/models_/aliases_/$name'
      path: '/models/aliases/$name'
      fullPath: '/models/aliases/$name'
      preLoaderRoute: typeof ModelsAliasesNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/model-evaluations_/$id_/languages': {
      id: '/model-evaluations_/$id_/languages'
      path: '/model-evaluations/$id/languages'
      fullPath: '/model-evaluations/$id/languages'
      preLoaderRoute: typeof ModelEvaluationsIdLanguagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/model-evaluations_/$id_/edit': {
      id: '/model-evaluations_/$id_/edit'
      path: '/model-evaluations/$id/edit'
      fullPath: '/model-evaluations/$id/edit'
      preLoaderRoute: typeof ModelEvaluationsIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/model-evaluations_/$id_/corpus': {
      id: '/model-evaluations_/$id_/corpus'
      path: '/model-evaluations/$id/corpus'
      fullPath: '/model-evaluations/$id/corpus'
      preLoaderRoute: typeof ModelEvaluationsIdCorpusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/model-evaluations_/$evaluationID/report': {
      id: '/model-evaluations_/$evaluationID/report'
      path: '/model-evaluations/$evaluationID/report'
      fullPath: '/model-evaluations/$evaluationID/report'
      preLoaderRoute: typeof ModelEvaluationsEvaluationIDReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/event-sources_/$id_/edit': {
      id: '/event-sources_/$id_/edit'
      path: '/event-sources/$id/edit'
      fullPath: '/event-sources/$id/edit'
      preLoaderRoute: typeof EventSourcesIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent/workflows_/settings': {
      id: '/agent/workflows_/settings'
      path: '/workflows/settings'
      fullPath: '/agent/workflows/settings'
      preLoaderRoute: typeof AgentWorkflowsSettingsRouteImport
      parentRoute: typeof AgentRoute
    }
    '/agent/workflows_/runs': {
      id: '/agent/workflows_/runs'
      path: '/workflows/runs'
      fullPath: '/agent/workflows/runs'
      preLoaderRoute: typeof AgentWorkflowsRunsRouteImport
      parentRoute: typeof AgentRoute
    }
    '/agent/workflows_/new': {
      id: '/agent/workflows_/new'
      path: '/workflows/new'
      fullPath: '/agent/workflows/new'
      preLoaderRoute: typeof AgentWorkflowsNewRouteImport
      parentRoute: typeof AgentRoute
    }
    '/agent/workflows_/$id': {
      id: '/agent/workflows_/$id'
      path: '/workflows/$id'
      fullPath: '/agent/workflows/$id'
      preLoaderRoute: typeof AgentWorkflowsIdRouteImport
      parentRoute: typeof AgentRoute
    }
    '/agent/tools_/$id': {
      id: '/agent/tools_/$id'
      path: '/tools/$id'
      fullPath: '/agent/tools/$id'
      preLoaderRoute: typeof AgentToolsIdRouteImport
      parentRoute: typeof AgentRoute
    }
    '/agent/skills_/new': {
      id: '/agent/skills_/new'
      path: '/skills/new'
      fullPath: '/agent/skills/new'
      preLoaderRoute: typeof AgentSkillsNewRouteImport
      parentRoute: typeof AgentRoute
    }
    '/agent/skills_/$id': {
      id: '/agent/skills_/$id'
      path: '/skills/$id'
      fullPath: '/agent/skills/$id'
      preLoaderRoute: typeof AgentSkillsIdRouteImport
      parentRoute: typeof AgentRoute
    }
    '/agent/mcp_/settings': {
      id: '/agent/mcp_/settings'
      path: '/mcp/settings'
      fullPath: '/agent/mcp/settings'
      preLoaderRoute: typeof AgentMcpSettingsRouteImport
      parentRoute: typeof AgentRoute
    }
    '/agent/mcp_/servers': {
      id: '/agent/mcp_/servers'
      path: '/mcp/servers'
      fullPath: '/agent/mcp/servers'
      preLoaderRoute: typeof AgentMcpServersRouteImport
      parentRoute: typeof AgentRoute
    }
    '/agent/git-workspaces_/settings': {
      id: '/agent/git-workspaces_/settings'
      path: '/git-workspaces/settings'
      fullPath: '/agent/git-workspaces/settings'
      preLoaderRoute: typeof AgentGitWorkspacesSettingsRouteImport
      parentRoute: typeof AgentRoute
    }
    '/agent/git-workspaces_/history': {
      id: '/agent/git-workspaces_/history'
      path: '/git-workspaces/history'
      fullPath: '/agent/git-workspaces/history'
      preLoaderRoute: typeof AgentGitWorkspacesHistoryRouteImport
      parentRoute: typeof AgentRoute
    }
    '/agent/git-workspaces_/$id': {
      id: '/agent/git-workspaces_/$id'
      path: '/git-workspaces/$id'
      fullPath: '/agent/git-workspaces/$id'
      preLoaderRoute: typeof AgentGitWorkspacesIdRouteImport
      parentRoute: typeof AgentRoute
    }
    '/agent/agents_/new': {
      id: '/agent/agents_/new'
      path: '/agents/new'
      fullPath: '/agent/agents/new'
      preLoaderRoute: typeof AgentAgentsNewRouteImport
      parentRoute: typeof AgentRoute
    }
    '/agent/agents_/$id': {
      id: '/agent/agents_/$id'
      path: '/agents/$id'
      fullPath: '/agent/agents/$id'
      preLoaderRoute: typeof AgentAgentsIdRouteImport
      parentRoute: typeof AgentRoute
    }
    '/accounts_/routers_/new': {
      id: '/accounts_/routers_/new'
      path: '/accounts/routers/new'
      fullPath: '/accounts/routers/new'
      preLoaderRoute: typeof AccountsRoutersNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounts_/routers_/$id': {
      id: '/accounts_/routers_/$id'
      path: '/accounts/routers/$id'
      fullPath: '/accounts/routers/$id'
      preLoaderRoute: typeof AccountsRoutersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounts_/$id_/edit': {
      id: '/accounts_/$id_/edit'
      path: '/accounts/$id/edit'
      fullPath: '/accounts/$id/edit'
      preLoaderRoute: typeof AccountsIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/repository-reviews_/repositories_/$id_/findings': {
      id: '/repository-reviews_/repositories_/$id_/findings'
      path: '/repository-reviews/repositories/$id/findings'
      fullPath: '/repository-reviews/repositories/$id/findings'
      preLoaderRoute: typeof RepositoryReviewsRepositoriesIdFindingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/repository-reviews_/repositories_/$id_/edit': {
      id: '/repository-reviews_/repositories_/$id_/edit'
      path: '/repository-reviews/repositories/$id/edit'
      fullPath: '/repository-reviews/repositories/$id/edit'
      preLoaderRoute: typeof RepositoryReviewsRepositoriesIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/repository-reviews_/profiles_/$profileID_/edit': {
      id: '/repository-reviews_/profiles_/$profileID_/edit'
      path: '/repository-reviews/profiles/$profileID/edit'
      fullPath: '/repository-reviews/profiles/$profileID/edit'
      preLoaderRoute: typeof RepositoryReviewsProfilesProfileIDEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/repository-reviews_/$id_/issues_/$draftId': {
      id: '/repository-reviews_/$id_/issues_/$draftId'
      path: '/repository-reviews/$id/issues/$draftId'
      fullPath: '/repository-reviews/$id/issues/$draftId'
      preLoaderRoute: typeof RepositoryReviewsIdIssuesDraftIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/repository-reviews_/$id_/findings_/$findingId': {
      id: '/repository-reviews_/$id_/findings_/$findingId'
      path: '/repository-reviews/$id/findings/$findingId'
      fullPath: '/repository-reviews/$id/findings/$findingId'
      preLoaderRoute: typeof RepositoryReviewsIdFindingsFindingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/models_/routers_/$name_/edit': {
      id: '/models_/routers_/$name_/edit'
      path: '/models/routers/$name/edit'
      fullPath: '/models/routers/$name/edit'
      preLoaderRoute: typeof ModelsRoutersNameEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/models_/aliases_/$name_/edit': {
      id: '/models_/aliases_/$name_/edit'
      path: '/models/aliases/$name/edit'
      fullPath: '/models/aliases/$name/edit'
      preLoaderRoute: typeof ModelsAliasesNameEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent/workflows_/runs_/$id': {
      id: '/agent/workflows_/runs_/$id'
      path: '/workflows/runs/$id'
      fullPath: '/agent/workflows/runs/$id'
      preLoaderRoute: typeof AgentWorkflowsRunsIdRouteImport
      parentRoute: typeof AgentRoute
    }
    '/agent/workflows_/$id_/edit': {
      id: '/agent/workflows_/$id_/edit'
      path: '/workflows/$id/edit'
      fullPath: '/agent/workflows/$id/edit'
      preLoaderRoute: typeof AgentWorkflowsIdEditRouteImport
      parentRoute: typeof AgentRoute
    }
    '/agent/tools_/settings_/adaptation': {
      id: '/agent/tools_/settings_/adaptation'
      path: '/tools/settings/adaptation'
      fullPath: '/agent/tools/settings/adaptation'
      preLoaderRoute: typeof AgentToolsSettingsAdaptationRouteImport
      parentRoute: typeof AgentRoute
    }
    '/agent/tools_/$id_/edit': {
      id: '/agent/tools_/$id_/edit'
      path: '/tools/$id/edit'
      fullPath: '/agent/tools/$id/edit'
      preLoaderRoute: typeof AgentToolsIdEditRouteImport
      parentRoute: typeof AgentRoute
    }
    '/agent/mcp_/servers_/new': {
      id: '/agent/mcp_/servers_/new'
      path: '/mcp/servers/new'
      fullPath: '/agent/mcp/servers/new'
      preLoaderRoute: typeof AgentMcpServersNewRouteImport
      parentRoute: typeof AgentRoute
    }
    '/agent/mcp_/servers_/$name': {
      id: '/agent/mcp_/servers_/$name'
      path: '/mcp/servers/$name'
      fullPath: '/agent/mcp/servers/$name'
      preLoaderRoute: typeof AgentMcpServersNameRouteImport
      parentRoute: typeof AgentRoute
    }
    '/agent/agents_/$id_/edit': {
      id: '/agent/agents_/$id_/edit'
      path: '/agents/$id/edit'
      fullPath: '/agent/agents/$id/edit'
      preLoaderRoute: typeof AgentAgentsIdEditRouteImport
      parentRoute: typeof AgentRoute
    }
    '/agent/agents_/$id_/capabilities': {
      id: '/agent/agents_/$id_/capabilities'
      path: '/agents/$id/capabilities'
      fullPath: '/agent/agents/$id/capabilities'
      preLoaderRoute: typeof AgentAgentsIdCapabilitiesRouteImport
      parentRoute: typeof AgentRoute
    }
    '/agent/agents_/$id_/activity': {
      id: '/agent/agents_/$id_/activity'
      path: '/agents/$id/activity'
      fullPath: '/agent/agents/$id/activity'
      preLoaderRoute: typeof AgentAgentsIdActivityRouteImport
      parentRoute: typeof AgentRoute
    }
    '/accounts_/routers_/$id_/edit': {
      id: '/accounts_/routers_/$id_/edit'
      path: '/accounts/routers/$id/edit'
      fullPath: '/accounts/routers/$id/edit'
      preLoaderRoute: typeof AccountsRoutersIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/repository-reviews_/repositories_/$id_/findings_/$findingId': {
      id: '/repository-reviews_/repositories_/$id_/findings_/$findingId'
      path: '/repository-reviews/repositories/$id/findings/$findingId'
      fullPath: '/repository-reviews/repositories/$id/findings/$findingId'
      preLoaderRoute: typeof RepositoryReviewsRepositoriesIdFindingsFindingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/repository-reviews_/$id_/findings_/$findingId_/link-issue': {
      id: '/repository-reviews_/$id_/findings_/$findingId_/link-issue'
      path: '/repository-reviews/$id/findings/$findingId/link-issue'
      fullPath: '/repository-reviews/$id/findings/$findingId/link-issue'
      preLoaderRoute: typeof RepositoryReviewsIdFindingsFindingIdLinkIssueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent/mcp_/servers_/$name_/edit': {
      id: '/agent/mcp_/servers_/$name_/edit'
      path: '/mcp/servers/$name/edit'
      fullPath: '/agent/mcp/servers/$name/edit'
      preLoaderRoute: typeof AgentMcpServersNameEditRouteImport
      parentRoute: typeof AgentRoute
    }
    '/repository-reviews_/repositories_/$id_/findings_/$findingId_/link-issue': {
      id: '/repository-reviews_/repositories_/$id_/findings_/$findingId_/link-issue'
      path: '/repository-reviews/repositories/$id/findings/$findingId/link-issue'
      fullPath: '/repository-reviews/repositories/$id/findings/$findingId/link-issue'
      preLoaderRoute: typeof RepositoryReviewsRepositoriesIdFindingsFindingIdLinkIssueRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ChannelsRouteRouteChildren {
  ChannelsNameRoute: typeof ChannelsNameRoute
}

const ChannelsRouteRouteChildren: ChannelsRouteRouteChildren = {
  ChannelsNameRoute: ChannelsNameRoute,
}

const ChannelsRouteRouteWithChildren = ChannelsRouteRoute._addFileChildren(
  ChannelsRouteRouteChildren,
)

interface AgentRouteChildren {
  AgentAgentsRoute: typeof AgentAgentsRoute
  AgentGitWorkspacesRoute: typeof AgentGitWorkspacesRoute
  AgentHubRoute: typeof AgentHubRoute
  AgentSkillsRoute: typeof AgentSkillsRoute
  AgentToolsRoute: typeof AgentToolsRoute
  AgentWorkflowsRoute: typeof AgentWorkflowsRoute
  AgentAgentsIdRoute: typeof AgentAgentsIdRoute
  AgentAgentsNewRoute: typeof AgentAgentsNewRoute
  AgentGitWorkspacesIdRoute: typeof AgentGitWorkspacesIdRoute
  AgentGitWorkspacesHistoryRoute: typeof AgentGitWorkspacesHistoryRoute
  AgentGitWorkspacesSettingsRoute: typeof AgentGitWorkspacesSettingsRoute
  AgentMcpServersRoute: typeof AgentMcpServersRoute
  AgentMcpSettingsRoute: typeof AgentMcpSettingsRoute
  AgentSkillsIdRoute: typeof AgentSkillsIdRoute
  AgentSkillsNewRoute: typeof AgentSkillsNewRoute
  AgentToolsIdRoute: typeof AgentToolsIdRoute
  AgentWorkflowsIdRoute: typeof AgentWorkflowsIdRoute
  AgentWorkflowsNewRoute: typeof AgentWorkflowsNewRoute
  AgentWorkflowsRunsRoute: typeof AgentWorkflowsRunsRoute
  AgentWorkflowsSettingsRoute: typeof AgentWorkflowsSettingsRoute
  AgentAgentsIdActivityRoute: typeof AgentAgentsIdActivityRoute
  AgentAgentsIdCapabilitiesRoute: typeof AgentAgentsIdCapabilitiesRoute
  AgentAgentsIdEditRoute: typeof AgentAgentsIdEditRoute
  AgentMcpServersNameRoute: typeof AgentMcpServersNameRoute
  AgentMcpServersNewRoute: typeof AgentMcpServersNewRoute
  AgentToolsIdEditRoute: typeof AgentToolsIdEditRoute
  AgentToolsSettingsAdaptationRoute: typeof AgentToolsSettingsAdaptationRoute
  AgentWorkflowsIdEditRoute: typeof AgentWorkflowsIdEditRoute
  AgentWorkflowsRunsIdRoute: typeof AgentWorkflowsRunsIdRoute
  AgentMcpServersNameEditRoute: typeof AgentMcpServersNameEditRoute
}

const AgentRouteChildren: AgentRouteChildren = {
  AgentAgentsRoute: AgentAgentsRoute,
  AgentGitWorkspacesRoute: AgentGitWorkspacesRoute,
  AgentHubRoute: AgentHubRoute,
  AgentSkillsRoute: AgentSkillsRoute,
  AgentToolsRoute: AgentToolsRoute,
  AgentWorkflowsRoute: AgentWorkflowsRoute,
  AgentAgentsIdRoute: AgentAgentsIdRoute,
  AgentAgentsNewRoute: AgentAgentsNewRoute,
  AgentGitWorkspacesIdRoute: AgentGitWorkspacesIdRoute,
  AgentGitWorkspacesHistoryRoute: AgentGitWorkspacesHistoryRoute,
  AgentGitWorkspacesSettingsRoute: AgentGitWorkspacesSettingsRoute,
  AgentMcpServersRoute: AgentMcpServersRoute,
  AgentMcpSettingsRoute: AgentMcpSettingsRoute,
  AgentSkillsIdRoute: AgentSkillsIdRoute,
  AgentSkillsNewRoute: AgentSkillsNewRoute,
  AgentToolsIdRoute: AgentToolsIdRoute,
  AgentWorkflowsIdRoute: AgentWorkflowsIdRoute,
  AgentWorkflowsNewRoute: AgentWorkflowsNewRoute,
  AgentWorkflowsRunsRoute: AgentWorkflowsRunsRoute,
  AgentWorkflowsSettingsRoute: AgentWorkflowsSettingsRoute,
  AgentAgentsIdActivityRoute: AgentAgentsIdActivityRoute,
  AgentAgentsIdCapabilitiesRoute: AgentAgentsIdCapabilitiesRoute,
  AgentAgentsIdEditRoute: AgentAgentsIdEditRoute,
  AgentMcpServersNameRoute: AgentMcpServersNameRoute,
  AgentMcpServersNewRoute: AgentMcpServersNewRoute,
  AgentToolsIdEditRoute: AgentToolsIdEditRoute,
  AgentToolsSettingsAdaptationRoute: AgentToolsSettingsAdaptationRoute,
  AgentWorkflowsIdEditRoute: AgentWorkflowsIdEditRoute,
  AgentWorkflowsRunsIdRoute: AgentWorkflowsRunsIdRoute,
  AgentMcpServersNameEditRoute: AgentMcpServersNameEditRoute,
}

const AgentRouteWithChildren = AgentRoute._addFileChildren(AgentRouteChildren)

interface ConfigRouteChildren {
  ConfigRawRoute: typeof ConfigRawRoute
}

const ConfigRouteChildren: ConfigRouteChildren = {
  ConfigRawRoute: ConfigRawRoute,
}

const ConfigRouteWithChildren =
  ConfigRoute._addFileChildren(ConfigRouteChildren)

interface ThreadsOpenRouteChildren {
  ThreadsOpenThreadIdRoute: typeof ThreadsOpenThreadIdRoute
}

const ThreadsOpenRouteChildren: ThreadsOpenRouteChildren = {
  ThreadsOpenThreadIdRoute: ThreadsOpenThreadIdRoute,
}

const ThreadsOpenRouteWithChildren = ThreadsOpenRoute._addFileChildren(
  ThreadsOpenRouteChildren,
)

interface ThreadsRouteChildren {
  ThreadsThreadIdRoute: typeof ThreadsThreadIdRoute
  ThreadsOpenRoute: typeof ThreadsOpenRouteWithChildren
  ThreadsSearchRoute: typeof ThreadsSearchRoute
}

const ThreadsRouteChildren: ThreadsRouteChildren = {
  ThreadsThreadIdRoute: ThreadsThreadIdRoute,
  ThreadsOpenRoute: ThreadsOpenRouteWithChildren,
  ThreadsSearchRoute: ThreadsSearchRoute,
}

const ThreadsRouteWithChildren =
  ThreadsRoute._addFileChildren(ThreadsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChannelsRouteRoute: ChannelsRouteRouteWithChildren,
  AccountsRoute: AccountsRoute,
  AgentRoute: AgentRouteWithChildren,
  ConfigRoute: ConfigRouteWithChildren,
  DevelopmentRoute: DevelopmentRoute,
  EventSourcesRoute: EventSourcesRoute,
  EventsRoute: EventsRoute,
  LauncherLoginRoute: LauncherLoginRoute,
  LauncherSetupRoute: LauncherSetupRoute,
  LogsRoute: LogsRoute,
  ModelEvaluationsRoute: ModelEvaluationsRoute,
  NotificationsRoute: NotificationsRoute,
  RepositoryReviewsRoute: RepositoryReviewsRoute,
  ThreadsRoute: ThreadsRouteWithChildren,
  AccountsIdRoute: AccountsIdRoute,
  AccountsNewRoute: AccountsNewRoute,
  AccountsRoutersRoute: AccountsRoutersRoute,
  DevelopmentWorkspaceIDRoute: DevelopmentWorkspaceIDRoute,
  DevelopmentNewRoute: DevelopmentNewRoute,
  DevelopmentRepositoriesRoute: DevelopmentRepositoriesRoute,
  DevelopmentSettingsRoute: DevelopmentSettingsRoute,
  DevelopmentWorkflowConfigurationsRoute:
    DevelopmentWorkflowConfigurationsRoute,
  EventSourcesIdRoute: EventSourcesIdRoute,
  EventSourcesNewRoute: EventSourcesNewRoute,
  EventSourcesSettingsRoute: EventSourcesSettingsRoute,
  ModelEvaluationsIdRoute: ModelEvaluationsIdRoute,
  ModelEvaluationsNewRoute: ModelEvaluationsNewRoute,
  ModelsAliasesRoute: ModelsAliasesRoute,
  ModelsRoutersRoute: ModelsRoutersRoute,
  NotificationsNotificationIDRoute: NotificationsNotificationIDRoute,
  RepositoryReviewsIdRoute: RepositoryReviewsIdRoute,
  RepositoryReviewsProfilesRoute: RepositoryReviewsProfilesRoute,
  RepositoryReviewsRepositoriesRoute: RepositoryReviewsRepositoriesRoute,
  RepositoryReviewsResultsRoute: RepositoryReviewsResultsRoute,
  AccountsIdEditRoute: AccountsIdEditRoute,
  AccountsRoutersIdRoute: AccountsRoutersIdRoute,
  AccountsRoutersNewRoute: AccountsRoutersNewRoute,
  EventSourcesIdEditRoute: EventSourcesIdEditRoute,
  ModelEvaluationsEvaluationIDReportRoute:
    ModelEvaluationsEvaluationIDReportRoute,
  ModelEvaluationsIdCorpusRoute: ModelEvaluationsIdCorpusRoute,
  ModelEvaluationsIdEditRoute: ModelEvaluationsIdEditRoute,
  ModelEvaluationsIdLanguagesRoute: ModelEvaluationsIdLanguagesRoute,
  ModelsAliasesNameRoute: ModelsAliasesNameRoute,
  ModelsAliasesNewRoute: ModelsAliasesNewRoute,
  ModelsRoutersNameRoute: ModelsRoutersNameRoute,
  ModelsRoutersNewRoute: ModelsRoutersNewRoute,
  RepositoryReviewsIdFindingsRoute: RepositoryReviewsIdFindingsRoute,
  RepositoryReviewsIdIssuesRoute: RepositoryReviewsIdIssuesRoute,
  RepositoryReviewsIdReportRoute: RepositoryReviewsIdReportRoute,
  RepositoryReviewsProfilesProfileIDRoute:
    RepositoryReviewsProfilesProfileIDRoute,
  RepositoryReviewsProfilesNewRoute: RepositoryReviewsProfilesNewRoute,
  RepositoryReviewsRepositoriesIdRoute: RepositoryReviewsRepositoriesIdRoute,
  RepositoryReviewsRepositoriesNewRoute: RepositoryReviewsRepositoriesNewRoute,
  AccountsRoutersIdEditRoute: AccountsRoutersIdEditRoute,
  ModelsAliasesNameEditRoute: ModelsAliasesNameEditRoute,
  ModelsRoutersNameEditRoute: ModelsRoutersNameEditRoute,
  RepositoryReviewsIdFindingsFindingIdRoute:
    RepositoryReviewsIdFindingsFindingIdRoute,
  RepositoryReviewsIdIssuesDraftIdRoute: RepositoryReviewsIdIssuesDraftIdRoute,
  RepositoryReviewsProfilesProfileIDEditRoute:
    RepositoryReviewsProfilesProfileIDEditRoute,
  RepositoryReviewsRepositoriesIdEditRoute:
    RepositoryReviewsRepositoriesIdEditRoute,
  RepositoryReviewsRepositoriesIdFindingsRoute:
    RepositoryReviewsRepositoriesIdFindingsRoute,
  RepositoryReviewsIdFindingsFindingIdLinkIssueRoute:
    RepositoryReviewsIdFindingsFindingIdLinkIssueRoute,
  RepositoryReviewsRepositoriesIdFindingsFindingIdRoute:
    RepositoryReviewsRepositoriesIdFindingsFindingIdRoute,
  RepositoryReviewsRepositoriesIdFindingsFindingIdLinkIssueRoute:
    RepositoryReviewsRepositoriesIdFindingsFindingIdLinkIssueRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
